# BUILD FILE SYNTAX: SKYLARK
# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.
load("//:LITHO_DEFS.bzl", "LITHO_JSR_TARGET", "LITHO_PROGUARDANNOTATIONS_TARGET", "LITHO_SOLOADER_TARGET", "fb_java_library")

fb_java_library(
    name = "jni",
    srcs = glob(["**/*.java"]),
    proguard_config = "fbjni.pro",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        LITHO_PROGUARDANNOTATIONS_TARGET,
        LITHO_SOLOADER_TARGET,
        LITHO_JSR_TARGET,
    ],
)
