# BUILD FILE SYNTAX: SKYLARK
# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load("//:LITHO_DEFS.bzl", "LITHO_VISIBILITY", "fb_xplat_cxx_library")

fb_xplat_cxx_library(
    name = "jni-hack",
    header_namespace = "",
    exported_headers = [
        "jni.h",
        "real/jni.h",
    ],
    force_static = True,
    visibility = LITHO_VISIBILITY,
)
