# BUILD FILE SYNTAX: SKYLARK
load("@xplat//configurations/buck/android:fb_android_library.bzl", "fb_android_library")

fb_android_library(
    name = "testing",
    srcs = glob(["*.java"]),
    visibility = [
        "//javatests/com/facebook/sonar/...",
    ],
    deps = [
        "//java/com/facebook/sonar:sonar",
    ],
)
