# BUILD FILE SYNTAX: SKYLARK
# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load("//:LITHO_DEFS.bzl", "define_fbjni_targets")

define_fbjni_targets()
