project 'Sample.xcodeproj'
source 'https://github.com/facebook/Sonar.git'
source 'https://github.com/CocoaPods/Specs'
swift_version = "4.1"

target 'Sample' do
  platform :ios, '9.0'
  pod 'FlipperKit', :path => '../../FlipperKit.podspec'
  pod 'FlipperKit/FlipperKitLayoutComponentKitSupport', :path => '../../FlipperKit.podspec'
  pod 'FlipperKit/SKIOSNetworkPlugin', :path => '../../FlipperKit.podspec'
  pod 'FlipperKit/FlipperKitUserDefaultsPlugin', :path => '../../FlipperKit.podspec'
  pod 'FlipperKit/FlipperKitExamplePlugin', :path => '../../FlipperKit.podspec'
  pod 'Flipper', :path => '../../Flipper.podspec'
  post_install do |installer|

        installer.pods_project.targets.each do |target|
            if ['YogaKit'].include? target.name
                target.build_configurations.each do |config|
                    config.build_settings['SWIFT_VERSION'] = swift_version
                end
            end
        end
    end

end
