project 'Sample.xcodeproj'
source '/Users/noahgilmore/CocoaPods/Local'
source 'https://github.com/facebook/Sonar.git'
source 'https://github.com/CocoaPods/Specs'
swift_version = "4.1"

target 'Sample' do
  pod 'SonarKit', :path => '../../'
  pod 'SonarKit/SonarKitLayoutComponentKitSupport', :path => '../../'
  pod 'SonarKit/SKIOSNetworkPlugin', :path => '../../'

  post_install do |installer|

        installer.pods_project.targets.each do |target|
            if ['YogaKit'].include? target.name
                target.build_configurations.each do |config|
                    config.build_settings['SWIFT_VERSION'] = swift_version
                end
            end
        end
    end

end
