# BUILD FILE SYNTAX: SKYLARK
load("@xplat//configurations/buck/android:fb_android_library.bzl", "fb_android_library")
load("//java/com/facebook/sonar:sonar_defs.bzl", "supported_apps")

fb_android_library(
    name = "inspector",
    srcs = glob(["**/*.java"]),
    provided_deps = [
        "//third-party/android/support/v4:lib-support-v4",
    ],
    source_only_abi_deps = ["//java/com/facebook/sonar/core:core"],
    tests = ["//javatests/com/facebook/sonar/plugins/oss/inspector:inspector"],
    visibility = [
        "//java/com/facebook/sonar/...",
        "//java/com/facebook/litho/sonar:sonar",
        "//java/com/facebook/componentscript/sonar:sonar",
        "//java/com/instagram/process/common:common",
        "//java/com/instagram/process/common/impl:impl",
        "//java/com/oculus/twilight:twilight",
    ] + supported_apps,
    deps = [
        "//android_res/com/facebook/sonar/plugins/inspector:inspector",
        "//java/com/facebook/sonar:sonar",
        "//java/com/facebook/sonar/plugins/oss/common:common",
        "//java/com/facebook/sonar/plugins/oss/console/iface:iface",
        "//third-party/java/jsr-305:jsr-305",
        "//third-party/java/stetho:stetho",
    ],
)
