// flow-typed signature: 4c4fcc7d39703336b04af263e250bdd1
// flow-typed version: <<STUB>>/adbkit-logcat-fb_v1.1.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'adbkit-logcat-fb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'adbkit-logcat-fb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'adbkit-logcat-fb/lib/logcat' {
  declare module.exports: any;
}

declare module 'adbkit-logcat-fb/lib/logcat/entry' {
  declare module.exports: any;
}

declare module 'adbkit-logcat-fb/lib/logcat/parser' {
  declare module.exports: any;
}

declare module 'adbkit-logcat-fb/lib/logcat/parser/binary' {
  declare module.exports: any;
}

declare module 'adbkit-logcat-fb/lib/logcat/priority' {
  declare module.exports: any;
}

declare module 'adbkit-logcat-fb/lib/logcat/reader' {
  declare module.exports: any;
}

declare module 'adbkit-logcat-fb/lib/logcat/transform' {
  declare module.exports: any;
}

// Filename aliases
declare module 'adbkit-logcat-fb/index' {
  declare module.exports: $Exports<'adbkit-logcat-fb'>;
}
declare module 'adbkit-logcat-fb/index.js' {
  declare module.exports: $Exports<'adbkit-logcat-fb'>;
}
declare module 'adbkit-logcat-fb/lib/logcat.js' {
  declare module.exports: $Exports<'adbkit-logcat-fb/lib/logcat'>;
}
declare module 'adbkit-logcat-fb/lib/logcat/entry.js' {
  declare module.exports: $Exports<'adbkit-logcat-fb/lib/logcat/entry'>;
}
declare module 'adbkit-logcat-fb/lib/logcat/parser.js' {
  declare module.exports: $Exports<'adbkit-logcat-fb/lib/logcat/parser'>;
}
declare module 'adbkit-logcat-fb/lib/logcat/parser/binary.js' {
  declare module.exports: $Exports<'adbkit-logcat-fb/lib/logcat/parser/binary'>;
}
declare module 'adbkit-logcat-fb/lib/logcat/priority.js' {
  declare module.exports: $Exports<'adbkit-logcat-fb/lib/logcat/priority'>;
}
declare module 'adbkit-logcat-fb/lib/logcat/reader.js' {
  declare module.exports: $Exports<'adbkit-logcat-fb/lib/logcat/reader'>;
}
declare module 'adbkit-logcat-fb/lib/logcat/transform.js' {
  declare module.exports: $Exports<'adbkit-logcat-fb/lib/logcat/transform'>;
}
