// flow-typed signature: 875c28c0c6b9d87bf9f38c8d13ddc599
// flow-typed version: <<STUB>>/address_v1.0.3/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'address'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'address' {
  declare module.exports: {
    ip: () => string,
    ipv6: () => string,
    mac: (callback: (err: ?Error, address: ?string) => mixed) => void,
  };
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'address/lib/address' {
  declare module.exports: any;
}

// Filename aliases
declare module 'address/lib/address.js' {
  declare module.exports: $Exports<'address/lib/address'>;
}
