// flow-typed signature: 3f26bdb86dbdfe57e7bf6c11d85e98e4
// flow-typed version: <<STUB>>/async-mutex_v0.1.3/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'async-mutex'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'async-mutex' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'async-mutex/lib/index' {
  declare module.exports: any;
}

declare module 'async-mutex/lib/Mutex' {
  declare module.exports: any;
}

declare module 'async-mutex/lib/MutexInterface' {
  declare module.exports: any;
}

// Filename aliases
declare module 'async-mutex/lib/index.js' {
  declare module.exports: $Exports<'async-mutex/lib/index'>;
}
declare module 'async-mutex/lib/Mutex.js' {
  declare module.exports: $Exports<'async-mutex/lib/Mutex'>;
}
declare module 'async-mutex/lib/MutexInterface.js' {
  declare module.exports: $Exports<'async-mutex/lib/MutexInterface'>;
}
