// flow-typed signature: d1d2d301b3f753cb6d40f8ac6d8df8c8
// flow-typed version: <<STUB>>/babel-code-frame_v^6.22.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-code-frame'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-code-frame' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-code-frame/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-code-frame/lib/index.js' {
  declare module.exports: $Exports<'babel-code-frame/lib/index'>;
}
