// flow-typed signature: 8f20b8fc8e610a76416674f109b1d8bc
// flow-typed version: <<STUB>>/babel-core_v7.0.0-alpha.12/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-core/lib/config/build-config-chain' {
  declare module.exports: any;
}

declare module 'babel-core/lib/config/caching' {
  declare module.exports: any;
}

declare module 'babel-core/lib/config/helpers/environment' {
  declare module.exports: any;
}

declare module 'babel-core/lib/config/index' {
  declare module.exports: any;
}

declare module 'babel-core/lib/config/loading/files/configuration' {
  declare module.exports: any;
}

declare module 'babel-core/lib/config/loading/files/index-browser' {
  declare module.exports: any;
}

declare module 'babel-core/lib/config/loading/files/index' {
  declare module.exports: any;
}

declare module 'babel-core/lib/config/loading/files/plugins' {
  declare module.exports: any;
}

declare module 'babel-core/lib/config/option-manager' {
  declare module.exports: any;
}

declare module 'babel-core/lib/config/plugin' {
  declare module.exports: any;
}

declare module 'babel-core/lib/config/removed' {
  declare module.exports: any;
}

declare module 'babel-core/lib/index' {
  declare module.exports: any;
}

declare module 'babel-core/lib/tools/build-external-helpers' {
  declare module.exports: any;
}

declare module 'babel-core/lib/transformation/file/index' {
  declare module.exports: any;
}

declare module 'babel-core/lib/transformation/file/metadata' {
  declare module.exports: any;
}

declare module 'babel-core/lib/transformation/internal-plugins/block-hoist' {
  declare module.exports: any;
}

declare module 'babel-core/lib/transformation/pipeline' {
  declare module.exports: any;
}

declare module 'babel-core/lib/transformation/plugin-pass' {
  declare module.exports: any;
}

declare module 'babel-core/lib/transformation/store' {
  declare module.exports: any;
}

declare module 'babel-core/register' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-core/index' {
  declare module.exports: $Exports<'babel-core'>;
}
declare module 'babel-core/index.js' {
  declare module.exports: $Exports<'babel-core'>;
}
declare module 'babel-core/lib/config/build-config-chain.js' {
  declare module.exports: $Exports<'babel-core/lib/config/build-config-chain'>;
}
declare module 'babel-core/lib/config/caching.js' {
  declare module.exports: $Exports<'babel-core/lib/config/caching'>;
}
declare module 'babel-core/lib/config/helpers/environment.js' {
  declare module.exports: $Exports<'babel-core/lib/config/helpers/environment'>;
}
declare module 'babel-core/lib/config/index.js' {
  declare module.exports: $Exports<'babel-core/lib/config/index'>;
}
declare module 'babel-core/lib/config/loading/files/configuration.js' {
  declare module.exports: $Exports<'babel-core/lib/config/loading/files/configuration'>;
}
declare module 'babel-core/lib/config/loading/files/index-browser.js' {
  declare module.exports: $Exports<'babel-core/lib/config/loading/files/index-browser'>;
}
declare module 'babel-core/lib/config/loading/files/index.js' {
  declare module.exports: $Exports<'babel-core/lib/config/loading/files/index'>;
}
declare module 'babel-core/lib/config/loading/files/plugins.js' {
  declare module.exports: $Exports<'babel-core/lib/config/loading/files/plugins'>;
}
declare module 'babel-core/lib/config/option-manager.js' {
  declare module.exports: $Exports<'babel-core/lib/config/option-manager'>;
}
declare module 'babel-core/lib/config/plugin.js' {
  declare module.exports: $Exports<'babel-core/lib/config/plugin'>;
}
declare module 'babel-core/lib/config/removed.js' {
  declare module.exports: $Exports<'babel-core/lib/config/removed'>;
}
declare module 'babel-core/lib/index.js' {
  declare module.exports: $Exports<'babel-core/lib/index'>;
}
declare module 'babel-core/lib/tools/build-external-helpers.js' {
  declare module.exports: $Exports<'babel-core/lib/tools/build-external-helpers'>;
}
declare module 'babel-core/lib/transformation/file/index.js' {
  declare module.exports: $Exports<'babel-core/lib/transformation/file/index'>;
}
declare module 'babel-core/lib/transformation/file/metadata.js' {
  declare module.exports: $Exports<'babel-core/lib/transformation/file/metadata'>;
}
declare module 'babel-core/lib/transformation/internal-plugins/block-hoist.js' {
  declare module.exports: $Exports<'babel-core/lib/transformation/internal-plugins/block-hoist'>;
}
declare module 'babel-core/lib/transformation/pipeline.js' {
  declare module.exports: $Exports<'babel-core/lib/transformation/pipeline'>;
}
declare module 'babel-core/lib/transformation/plugin-pass.js' {
  declare module.exports: $Exports<'babel-core/lib/transformation/plugin-pass'>;
}
declare module 'babel-core/lib/transformation/store.js' {
  declare module.exports: $Exports<'babel-core/lib/transformation/store'>;
}
declare module 'babel-core/register.js' {
  declare module.exports: $Exports<'babel-core/register'>;
}
