// flow-typed signature: f472557a9bcea4a046c88cdcdd21ff40
// flow-typed version: <<STUB>>/babylon_v7.0.0-beta.14/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babylon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babylon' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babylon/bin/babylon' {
  declare module.exports: any;
}

declare module 'babylon/bin/generate-identifier-regex' {
  declare module.exports: any;
}

declare module 'babylon/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babylon/bin/babylon.js' {
  declare module.exports: $Exports<'babylon/bin/babylon'>;
}
declare module 'babylon/bin/generate-identifier-regex.js' {
  declare module.exports: $Exports<'babylon/bin/generate-identifier-regex'>;
}
declare module 'babylon/lib/index.js' {
  declare module.exports: $Exports<'babylon/lib/index'>;
}
