// flow-typed signature: 1a1ca58820f1520ecf0c5cf5a814e16d
// flow-typed version: <<STUB>>/child-process-es6-promise_v1.2.1/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'child-process-es6-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'child-process-es6-promise' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'child-process-es6-promise/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'child-process-es6-promise/index' {
  declare module.exports: $Exports<'child-process-es6-promise'>;
}
declare module 'child-process-es6-promise/index.js' {
  declare module.exports: $Exports<'child-process-es6-promise'>;
}
declare module 'child-process-es6-promise/test.js' {
  declare module.exports: $Exports<'child-process-es6-promise/test'>;
}
