// flow-typed signature: 56334b937a6991fded5d2f2312821ccd
// flow-typed version: <<STUB>>/codemirror_v^5.25.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'codemirror'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'codemirror' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'codemirror/addon/comment/comment' {
  declare module.exports: any;
}

declare module 'codemirror/addon/comment/continuecomment' {
  declare module.exports: any;
}

declare module 'codemirror/addon/dialog/dialog' {
  declare module.exports: any;
}

declare module 'codemirror/addon/display/autorefresh' {
  declare module.exports: any;
}

declare module 'codemirror/addon/display/fullscreen' {
  declare module.exports: any;
}

declare module 'codemirror/addon/display/panel' {
  declare module.exports: any;
}

declare module 'codemirror/addon/display/placeholder' {
  declare module.exports: any;
}

declare module 'codemirror/addon/display/rulers' {
  declare module.exports: any;
}

declare module 'codemirror/addon/edit/closebrackets' {
  declare module.exports: any;
}

declare module 'codemirror/addon/edit/closetag' {
  declare module.exports: any;
}

declare module 'codemirror/addon/edit/continuelist' {
  declare module.exports: any;
}

declare module 'codemirror/addon/edit/matchbrackets' {
  declare module.exports: any;
}

declare module 'codemirror/addon/edit/matchtags' {
  declare module.exports: any;
}

declare module 'codemirror/addon/edit/trailingspace' {
  declare module.exports: any;
}

declare module 'codemirror/addon/fold/brace-fold' {
  declare module.exports: any;
}

declare module 'codemirror/addon/fold/comment-fold' {
  declare module.exports: any;
}

declare module 'codemirror/addon/fold/foldcode' {
  declare module.exports: any;
}

declare module 'codemirror/addon/fold/foldgutter' {
  declare module.exports: any;
}

declare module 'codemirror/addon/fold/indent-fold' {
  declare module.exports: any;
}

declare module 'codemirror/addon/fold/markdown-fold' {
  declare module.exports: any;
}

declare module 'codemirror/addon/fold/xml-fold' {
  declare module.exports: any;
}

declare module 'codemirror/addon/hint/anyword-hint' {
  declare module.exports: any;
}

declare module 'codemirror/addon/hint/css-hint' {
  declare module.exports: any;
}

declare module 'codemirror/addon/hint/html-hint' {
  declare module.exports: any;
}

declare module 'codemirror/addon/hint/javascript-hint' {
  declare module.exports: any;
}

declare module 'codemirror/addon/hint/show-hint' {
  declare module.exports: any;
}

declare module 'codemirror/addon/hint/sql-hint' {
  declare module.exports: any;
}

declare module 'codemirror/addon/hint/xml-hint' {
  declare module.exports: any;
}

declare module 'codemirror/addon/lint/coffeescript-lint' {
  declare module.exports: any;
}

declare module 'codemirror/addon/lint/css-lint' {
  declare module.exports: any;
}

declare module 'codemirror/addon/lint/html-lint' {
  declare module.exports: any;
}

declare module 'codemirror/addon/lint/javascript-lint' {
  declare module.exports: any;
}

declare module 'codemirror/addon/lint/json-lint' {
  declare module.exports: any;
}

declare module 'codemirror/addon/lint/lint' {
  declare module.exports: any;
}

declare module 'codemirror/addon/lint/yaml-lint' {
  declare module.exports: any;
}

declare module 'codemirror/addon/merge/merge' {
  declare module.exports: any;
}

declare module 'codemirror/addon/mode/loadmode' {
  declare module.exports: any;
}

declare module 'codemirror/addon/mode/multiplex_test' {
  declare module.exports: any;
}

declare module 'codemirror/addon/mode/multiplex' {
  declare module.exports: any;
}

declare module 'codemirror/addon/mode/overlay' {
  declare module.exports: any;
}

declare module 'codemirror/addon/mode/simple' {
  declare module.exports: any;
}

declare module 'codemirror/addon/runmode/colorize' {
  declare module.exports: any;
}

declare module 'codemirror/addon/runmode/runmode-standalone' {
  declare module.exports: any;
}

declare module 'codemirror/addon/runmode/runmode' {
  declare module.exports: any;
}

declare module 'codemirror/addon/runmode/runmode.node' {
  declare module.exports: any;
}

declare module 'codemirror/addon/scroll/annotatescrollbar' {
  declare module.exports: any;
}

declare module 'codemirror/addon/scroll/scrollpastend' {
  declare module.exports: any;
}

declare module 'codemirror/addon/scroll/simplescrollbars' {
  declare module.exports: any;
}

declare module 'codemirror/addon/search/jump-to-line' {
  declare module.exports: any;
}

declare module 'codemirror/addon/search/match-highlighter' {
  declare module.exports: any;
}

declare module 'codemirror/addon/search/matchesonscrollbar' {
  declare module.exports: any;
}

declare module 'codemirror/addon/search/search' {
  declare module.exports: any;
}

declare module 'codemirror/addon/search/searchcursor' {
  declare module.exports: any;
}

declare module 'codemirror/addon/selection/active-line' {
  declare module.exports: any;
}

declare module 'codemirror/addon/selection/mark-selection' {
  declare module.exports: any;
}

declare module 'codemirror/addon/selection/selection-pointer' {
  declare module.exports: any;
}

declare module 'codemirror/addon/tern/tern' {
  declare module.exports: any;
}

declare module 'codemirror/addon/tern/worker' {
  declare module.exports: any;
}

declare module 'codemirror/addon/wrap/hardwrap' {
  declare module.exports: any;
}

declare module 'codemirror/keymap/emacs' {
  declare module.exports: any;
}

declare module 'codemirror/keymap/sublime' {
  declare module.exports: any;
}

declare module 'codemirror/keymap/vim' {
  declare module.exports: any;
}

declare module 'codemirror/lib/codemirror' {
  declare module.exports: any;
}

declare module 'codemirror/mode/apl/apl' {
  declare module.exports: any;
}

declare module 'codemirror/mode/asciiarmor/asciiarmor' {
  declare module.exports: any;
}

declare module 'codemirror/mode/asn.1/asn.1' {
  declare module.exports: any;
}

declare module 'codemirror/mode/asterisk/asterisk' {
  declare module.exports: any;
}

declare module 'codemirror/mode/brainfuck/brainfuck' {
  declare module.exports: any;
}

declare module 'codemirror/mode/clike/clike' {
  declare module.exports: any;
}

declare module 'codemirror/mode/clojure/clojure' {
  declare module.exports: any;
}

declare module 'codemirror/mode/cmake/cmake' {
  declare module.exports: any;
}

declare module 'codemirror/mode/cobol/cobol' {
  declare module.exports: any;
}

declare module 'codemirror/mode/coffeescript/coffeescript' {
  declare module.exports: any;
}

declare module 'codemirror/mode/commonlisp/commonlisp' {
  declare module.exports: any;
}

declare module 'codemirror/mode/crystal/crystal' {
  declare module.exports: any;
}

declare module 'codemirror/mode/css/css' {
  declare module.exports: any;
}

declare module 'codemirror/mode/cypher/cypher' {
  declare module.exports: any;
}

declare module 'codemirror/mode/d/d' {
  declare module.exports: any;
}

declare module 'codemirror/mode/dart/dart' {
  declare module.exports: any;
}

declare module 'codemirror/mode/diff/diff' {
  declare module.exports: any;
}

declare module 'codemirror/mode/django/django' {
  declare module.exports: any;
}

declare module 'codemirror/mode/dockerfile/dockerfile' {
  declare module.exports: any;
}

declare module 'codemirror/mode/dtd/dtd' {
  declare module.exports: any;
}

declare module 'codemirror/mode/dylan/dylan' {
  declare module.exports: any;
}

declare module 'codemirror/mode/ebnf/ebnf' {
  declare module.exports: any;
}

declare module 'codemirror/mode/ecl/ecl' {
  declare module.exports: any;
}

declare module 'codemirror/mode/eiffel/eiffel' {
  declare module.exports: any;
}

declare module 'codemirror/mode/elm/elm' {
  declare module.exports: any;
}

declare module 'codemirror/mode/erlang/erlang' {
  declare module.exports: any;
}

declare module 'codemirror/mode/factor/factor' {
  declare module.exports: any;
}

declare module 'codemirror/mode/fcl/fcl' {
  declare module.exports: any;
}

declare module 'codemirror/mode/forth/forth' {
  declare module.exports: any;
}

declare module 'codemirror/mode/fortran/fortran' {
  declare module.exports: any;
}

declare module 'codemirror/mode/gas/gas' {
  declare module.exports: any;
}

declare module 'codemirror/mode/gfm/gfm' {
  declare module.exports: any;
}

declare module 'codemirror/mode/gherkin/gherkin' {
  declare module.exports: any;
}

declare module 'codemirror/mode/go/go' {
  declare module.exports: any;
}

declare module 'codemirror/mode/groovy/groovy' {
  declare module.exports: any;
}

declare module 'codemirror/mode/haml/haml' {
  declare module.exports: any;
}

declare module 'codemirror/mode/handlebars/handlebars' {
  declare module.exports: any;
}

declare module 'codemirror/mode/haskell-literate/haskell-literate' {
  declare module.exports: any;
}

declare module 'codemirror/mode/haskell/haskell' {
  declare module.exports: any;
}

declare module 'codemirror/mode/haxe/haxe' {
  declare module.exports: any;
}

declare module 'codemirror/mode/htmlembedded/htmlembedded' {
  declare module.exports: any;
}

declare module 'codemirror/mode/htmlmixed/htmlmixed' {
  declare module.exports: any;
}

declare module 'codemirror/mode/http/http' {
  declare module.exports: any;
}

declare module 'codemirror/mode/idl/idl' {
  declare module.exports: any;
}

declare module 'codemirror/mode/javascript/javascript' {
  declare module.exports: any;
}

declare module 'codemirror/mode/jinja2/jinja2' {
  declare module.exports: any;
}

declare module 'codemirror/mode/jsx/jsx' {
  declare module.exports: any;
}

declare module 'codemirror/mode/julia/julia' {
  declare module.exports: any;
}

declare module 'codemirror/mode/livescript/livescript' {
  declare module.exports: any;
}

declare module 'codemirror/mode/lua/lua' {
  declare module.exports: any;
}

declare module 'codemirror/mode/markdown/markdown' {
  declare module.exports: any;
}

declare module 'codemirror/mode/mathematica/mathematica' {
  declare module.exports: any;
}

declare module 'codemirror/mode/mbox/mbox' {
  declare module.exports: any;
}

declare module 'codemirror/mode/meta' {
  declare module.exports: any;
}

declare module 'codemirror/mode/mirc/mirc' {
  declare module.exports: any;
}

declare module 'codemirror/mode/mllike/mllike' {
  declare module.exports: any;
}

declare module 'codemirror/mode/modelica/modelica' {
  declare module.exports: any;
}

declare module 'codemirror/mode/mscgen/mscgen' {
  declare module.exports: any;
}

declare module 'codemirror/mode/mumps/mumps' {
  declare module.exports: any;
}

declare module 'codemirror/mode/nginx/nginx' {
  declare module.exports: any;
}

declare module 'codemirror/mode/nsis/nsis' {
  declare module.exports: any;
}

declare module 'codemirror/mode/ntriples/ntriples' {
  declare module.exports: any;
}

declare module 'codemirror/mode/octave/octave' {
  declare module.exports: any;
}

declare module 'codemirror/mode/oz/oz' {
  declare module.exports: any;
}

declare module 'codemirror/mode/pascal/pascal' {
  declare module.exports: any;
}

declare module 'codemirror/mode/pegjs/pegjs' {
  declare module.exports: any;
}

declare module 'codemirror/mode/perl/perl' {
  declare module.exports: any;
}

declare module 'codemirror/mode/php/php' {
  declare module.exports: any;
}

declare module 'codemirror/mode/pig/pig' {
  declare module.exports: any;
}

declare module 'codemirror/mode/powershell/powershell' {
  declare module.exports: any;
}

declare module 'codemirror/mode/properties/properties' {
  declare module.exports: any;
}

declare module 'codemirror/mode/protobuf/protobuf' {
  declare module.exports: any;
}

declare module 'codemirror/mode/pug/pug' {
  declare module.exports: any;
}

declare module 'codemirror/mode/puppet/puppet' {
  declare module.exports: any;
}

declare module 'codemirror/mode/python/python' {
  declare module.exports: any;
}

declare module 'codemirror/mode/q/q' {
  declare module.exports: any;
}

declare module 'codemirror/mode/r/r' {
  declare module.exports: any;
}

declare module 'codemirror/mode/rpm/rpm' {
  declare module.exports: any;
}

declare module 'codemirror/mode/rst/rst' {
  declare module.exports: any;
}

declare module 'codemirror/mode/ruby/ruby' {
  declare module.exports: any;
}

declare module 'codemirror/mode/rust/rust' {
  declare module.exports: any;
}

declare module 'codemirror/mode/sas/sas' {
  declare module.exports: any;
}

declare module 'codemirror/mode/sass/sass' {
  declare module.exports: any;
}

declare module 'codemirror/mode/scheme/scheme' {
  declare module.exports: any;
}

declare module 'codemirror/mode/shell/shell' {
  declare module.exports: any;
}

declare module 'codemirror/mode/sieve/sieve' {
  declare module.exports: any;
}

declare module 'codemirror/mode/slim/slim' {
  declare module.exports: any;
}

declare module 'codemirror/mode/smalltalk/smalltalk' {
  declare module.exports: any;
}

declare module 'codemirror/mode/smarty/smarty' {
  declare module.exports: any;
}

declare module 'codemirror/mode/solr/solr' {
  declare module.exports: any;
}

declare module 'codemirror/mode/soy/soy' {
  declare module.exports: any;
}

declare module 'codemirror/mode/sparql/sparql' {
  declare module.exports: any;
}

declare module 'codemirror/mode/spreadsheet/spreadsheet' {
  declare module.exports: any;
}

declare module 'codemirror/mode/sql/sql' {
  declare module.exports: any;
}

declare module 'codemirror/mode/stex/stex' {
  declare module.exports: any;
}

declare module 'codemirror/mode/stylus/stylus' {
  declare module.exports: any;
}

declare module 'codemirror/mode/swift/swift' {
  declare module.exports: any;
}

declare module 'codemirror/mode/tcl/tcl' {
  declare module.exports: any;
}

declare module 'codemirror/mode/textile/textile' {
  declare module.exports: any;
}

declare module 'codemirror/mode/tiddlywiki/tiddlywiki' {
  declare module.exports: any;
}

declare module 'codemirror/mode/tiki/tiki' {
  declare module.exports: any;
}

declare module 'codemirror/mode/toml/toml' {
  declare module.exports: any;
}

declare module 'codemirror/mode/tornado/tornado' {
  declare module.exports: any;
}

declare module 'codemirror/mode/troff/troff' {
  declare module.exports: any;
}

declare module 'codemirror/mode/ttcn-cfg/ttcn-cfg' {
  declare module.exports: any;
}

declare module 'codemirror/mode/ttcn/ttcn' {
  declare module.exports: any;
}

declare module 'codemirror/mode/turtle/turtle' {
  declare module.exports: any;
}

declare module 'codemirror/mode/twig/twig' {
  declare module.exports: any;
}

declare module 'codemirror/mode/vb/vb' {
  declare module.exports: any;
}

declare module 'codemirror/mode/vbscript/vbscript' {
  declare module.exports: any;
}

declare module 'codemirror/mode/velocity/velocity' {
  declare module.exports: any;
}

declare module 'codemirror/mode/verilog/verilog' {
  declare module.exports: any;
}

declare module 'codemirror/mode/vhdl/vhdl' {
  declare module.exports: any;
}

declare module 'codemirror/mode/vue/vue' {
  declare module.exports: any;
}

declare module 'codemirror/mode/webidl/webidl' {
  declare module.exports: any;
}

declare module 'codemirror/mode/xml/xml' {
  declare module.exports: any;
}

declare module 'codemirror/mode/xquery/xquery' {
  declare module.exports: any;
}

declare module 'codemirror/mode/yacas/yacas' {
  declare module.exports: any;
}

declare module 'codemirror/mode/yaml-frontmatter/yaml-frontmatter' {
  declare module.exports: any;
}

declare module 'codemirror/mode/yaml/yaml' {
  declare module.exports: any;
}

declare module 'codemirror/mode/z80/z80' {
  declare module.exports: any;
}

declare module 'codemirror/rollup.config' {
  declare module.exports: any;
}

declare module 'codemirror/src/codemirror' {
  declare module.exports: any;
}

declare module 'codemirror/src/display/Display' {
  declare module.exports: any;
}

declare module 'codemirror/src/display/focus' {
  declare module.exports: any;
}

declare module 'codemirror/src/display/gutters' {
  declare module.exports: any;
}

declare module 'codemirror/src/display/highlight_worker' {
  declare module.exports: any;
}

declare module 'codemirror/src/display/line_numbers' {
  declare module.exports: any;
}

declare module 'codemirror/src/display/mode_state' {
  declare module.exports: any;
}

declare module 'codemirror/src/display/operations' {
  declare module.exports: any;
}

declare module 'codemirror/src/display/scroll_events' {
  declare module.exports: any;
}

declare module 'codemirror/src/display/scrollbars' {
  declare module.exports: any;
}

declare module 'codemirror/src/display/scrolling' {
  declare module.exports: any;
}

declare module 'codemirror/src/display/selection' {
  declare module.exports: any;
}

declare module 'codemirror/src/display/update_display' {
  declare module.exports: any;
}

declare module 'codemirror/src/display/update_line' {
  declare module.exports: any;
}

declare module 'codemirror/src/display/update_lines' {
  declare module.exports: any;
}

declare module 'codemirror/src/display/view_tracking' {
  declare module.exports: any;
}

declare module 'codemirror/src/edit/CodeMirror' {
  declare module.exports: any;
}

declare module 'codemirror/src/edit/commands' {
  declare module.exports: any;
}

declare module 'codemirror/src/edit/deleteNearSelection' {
  declare module.exports: any;
}

declare module 'codemirror/src/edit/drop_events' {
  declare module.exports: any;
}

declare module 'codemirror/src/edit/fromTextArea' {
  declare module.exports: any;
}

declare module 'codemirror/src/edit/global_events' {
  declare module.exports: any;
}

declare module 'codemirror/src/edit/key_events' {
  declare module.exports: any;
}

declare module 'codemirror/src/edit/legacy' {
  declare module.exports: any;
}

declare module 'codemirror/src/edit/main' {
  declare module.exports: any;
}

declare module 'codemirror/src/edit/methods' {
  declare module.exports: any;
}

declare module 'codemirror/src/edit/mouse_events' {
  declare module.exports: any;
}

declare module 'codemirror/src/edit/options' {
  declare module.exports: any;
}

declare module 'codemirror/src/edit/utils' {
  declare module.exports: any;
}

declare module 'codemirror/src/input/ContentEditableInput' {
  declare module.exports: any;
}

declare module 'codemirror/src/input/indent' {
  declare module.exports: any;
}

declare module 'codemirror/src/input/input' {
  declare module.exports: any;
}

declare module 'codemirror/src/input/keymap' {
  declare module.exports: any;
}

declare module 'codemirror/src/input/keynames' {
  declare module.exports: any;
}

declare module 'codemirror/src/input/movement' {
  declare module.exports: any;
}

declare module 'codemirror/src/input/TextareaInput' {
  declare module.exports: any;
}

declare module 'codemirror/src/line/highlight' {
  declare module.exports: any;
}

declare module 'codemirror/src/line/line_data' {
  declare module.exports: any;
}

declare module 'codemirror/src/line/pos' {
  declare module.exports: any;
}

declare module 'codemirror/src/line/saw_special_spans' {
  declare module.exports: any;
}

declare module 'codemirror/src/line/spans' {
  declare module.exports: any;
}

declare module 'codemirror/src/line/utils_line' {
  declare module.exports: any;
}

declare module 'codemirror/src/measurement/position_measurement' {
  declare module.exports: any;
}

declare module 'codemirror/src/measurement/widgets' {
  declare module.exports: any;
}

declare module 'codemirror/src/model/change_measurement' {
  declare module.exports: any;
}

declare module 'codemirror/src/model/changes' {
  declare module.exports: any;
}

declare module 'codemirror/src/model/chunk' {
  declare module.exports: any;
}

declare module 'codemirror/src/model/Doc' {
  declare module.exports: any;
}

declare module 'codemirror/src/model/document_data' {
  declare module.exports: any;
}

declare module 'codemirror/src/model/history' {
  declare module.exports: any;
}

declare module 'codemirror/src/model/line_widget' {
  declare module.exports: any;
}

declare module 'codemirror/src/model/mark_text' {
  declare module.exports: any;
}

declare module 'codemirror/src/model/selection_updates' {
  declare module.exports: any;
}

declare module 'codemirror/src/model/selection' {
  declare module.exports: any;
}

declare module 'codemirror/src/modes' {
  declare module.exports: any;
}

declare module 'codemirror/src/util/bidi' {
  declare module.exports: any;
}

declare module 'codemirror/src/util/browser' {
  declare module.exports: any;
}

declare module 'codemirror/src/util/dom' {
  declare module.exports: any;
}

declare module 'codemirror/src/util/event' {
  declare module.exports: any;
}

declare module 'codemirror/src/util/feature_detection' {
  declare module.exports: any;
}

declare module 'codemirror/src/util/misc' {
  declare module.exports: any;
}

declare module 'codemirror/src/util/operation_group' {
  declare module.exports: any;
}

declare module 'codemirror/src/util/StringStream' {
  declare module.exports: any;
}

// Filename aliases
declare module 'codemirror/addon/comment/comment.js' {
  declare module.exports: $Exports<'codemirror/addon/comment/comment'>;
}
declare module 'codemirror/addon/comment/continuecomment.js' {
  declare module.exports: $Exports<'codemirror/addon/comment/continuecomment'>;
}
declare module 'codemirror/addon/dialog/dialog.js' {
  declare module.exports: $Exports<'codemirror/addon/dialog/dialog'>;
}
declare module 'codemirror/addon/display/autorefresh.js' {
  declare module.exports: $Exports<'codemirror/addon/display/autorefresh'>;
}
declare module 'codemirror/addon/display/fullscreen.js' {
  declare module.exports: $Exports<'codemirror/addon/display/fullscreen'>;
}
declare module 'codemirror/addon/display/panel.js' {
  declare module.exports: $Exports<'codemirror/addon/display/panel'>;
}
declare module 'codemirror/addon/display/placeholder.js' {
  declare module.exports: $Exports<'codemirror/addon/display/placeholder'>;
}
declare module 'codemirror/addon/display/rulers.js' {
  declare module.exports: $Exports<'codemirror/addon/display/rulers'>;
}
declare module 'codemirror/addon/edit/closebrackets.js' {
  declare module.exports: $Exports<'codemirror/addon/edit/closebrackets'>;
}
declare module 'codemirror/addon/edit/closetag.js' {
  declare module.exports: $Exports<'codemirror/addon/edit/closetag'>;
}
declare module 'codemirror/addon/edit/continuelist.js' {
  declare module.exports: $Exports<'codemirror/addon/edit/continuelist'>;
}
declare module 'codemirror/addon/edit/matchbrackets.js' {
  declare module.exports: $Exports<'codemirror/addon/edit/matchbrackets'>;
}
declare module 'codemirror/addon/edit/matchtags.js' {
  declare module.exports: $Exports<'codemirror/addon/edit/matchtags'>;
}
declare module 'codemirror/addon/edit/trailingspace.js' {
  declare module.exports: $Exports<'codemirror/addon/edit/trailingspace'>;
}
declare module 'codemirror/addon/fold/brace-fold.js' {
  declare module.exports: $Exports<'codemirror/addon/fold/brace-fold'>;
}
declare module 'codemirror/addon/fold/comment-fold.js' {
  declare module.exports: $Exports<'codemirror/addon/fold/comment-fold'>;
}
declare module 'codemirror/addon/fold/foldcode.js' {
  declare module.exports: $Exports<'codemirror/addon/fold/foldcode'>;
}
declare module 'codemirror/addon/fold/foldgutter.js' {
  declare module.exports: $Exports<'codemirror/addon/fold/foldgutter'>;
}
declare module 'codemirror/addon/fold/indent-fold.js' {
  declare module.exports: $Exports<'codemirror/addon/fold/indent-fold'>;
}
declare module 'codemirror/addon/fold/markdown-fold.js' {
  declare module.exports: $Exports<'codemirror/addon/fold/markdown-fold'>;
}
declare module 'codemirror/addon/fold/xml-fold.js' {
  declare module.exports: $Exports<'codemirror/addon/fold/xml-fold'>;
}
declare module 'codemirror/addon/hint/anyword-hint.js' {
  declare module.exports: $Exports<'codemirror/addon/hint/anyword-hint'>;
}
declare module 'codemirror/addon/hint/css-hint.js' {
  declare module.exports: $Exports<'codemirror/addon/hint/css-hint'>;
}
declare module 'codemirror/addon/hint/html-hint.js' {
  declare module.exports: $Exports<'codemirror/addon/hint/html-hint'>;
}
declare module 'codemirror/addon/hint/javascript-hint.js' {
  declare module.exports: $Exports<'codemirror/addon/hint/javascript-hint'>;
}
declare module 'codemirror/addon/hint/show-hint.js' {
  declare module.exports: $Exports<'codemirror/addon/hint/show-hint'>;
}
declare module 'codemirror/addon/hint/sql-hint.js' {
  declare module.exports: $Exports<'codemirror/addon/hint/sql-hint'>;
}
declare module 'codemirror/addon/hint/xml-hint.js' {
  declare module.exports: $Exports<'codemirror/addon/hint/xml-hint'>;
}
declare module 'codemirror/addon/lint/coffeescript-lint.js' {
  declare module.exports: $Exports<'codemirror/addon/lint/coffeescript-lint'>;
}
declare module 'codemirror/addon/lint/css-lint.js' {
  declare module.exports: $Exports<'codemirror/addon/lint/css-lint'>;
}
declare module 'codemirror/addon/lint/html-lint.js' {
  declare module.exports: $Exports<'codemirror/addon/lint/html-lint'>;
}
declare module 'codemirror/addon/lint/javascript-lint.js' {
  declare module.exports: $Exports<'codemirror/addon/lint/javascript-lint'>;
}
declare module 'codemirror/addon/lint/json-lint.js' {
  declare module.exports: $Exports<'codemirror/addon/lint/json-lint'>;
}
declare module 'codemirror/addon/lint/lint.js' {
  declare module.exports: $Exports<'codemirror/addon/lint/lint'>;
}
declare module 'codemirror/addon/lint/yaml-lint.js' {
  declare module.exports: $Exports<'codemirror/addon/lint/yaml-lint'>;
}
declare module 'codemirror/addon/merge/merge.js' {
  declare module.exports: $Exports<'codemirror/addon/merge/merge'>;
}
declare module 'codemirror/addon/mode/loadmode.js' {
  declare module.exports: $Exports<'codemirror/addon/mode/loadmode'>;
}
declare module 'codemirror/addon/mode/multiplex_test.js' {
  declare module.exports: $Exports<'codemirror/addon/mode/multiplex_test'>;
}
declare module 'codemirror/addon/mode/multiplex.js' {
  declare module.exports: $Exports<'codemirror/addon/mode/multiplex'>;
}
declare module 'codemirror/addon/mode/overlay.js' {
  declare module.exports: $Exports<'codemirror/addon/mode/overlay'>;
}
declare module 'codemirror/addon/mode/simple.js' {
  declare module.exports: $Exports<'codemirror/addon/mode/simple'>;
}
declare module 'codemirror/addon/runmode/colorize.js' {
  declare module.exports: $Exports<'codemirror/addon/runmode/colorize'>;
}
declare module 'codemirror/addon/runmode/runmode-standalone.js' {
  declare module.exports: $Exports<'codemirror/addon/runmode/runmode-standalone'>;
}
declare module 'codemirror/addon/runmode/runmode.js' {
  declare module.exports: $Exports<'codemirror/addon/runmode/runmode'>;
}
declare module 'codemirror/addon/runmode/runmode.node.js' {
  declare module.exports: $Exports<'codemirror/addon/runmode/runmode.node'>;
}
declare module 'codemirror/addon/scroll/annotatescrollbar.js' {
  declare module.exports: $Exports<'codemirror/addon/scroll/annotatescrollbar'>;
}
declare module 'codemirror/addon/scroll/scrollpastend.js' {
  declare module.exports: $Exports<'codemirror/addon/scroll/scrollpastend'>;
}
declare module 'codemirror/addon/scroll/simplescrollbars.js' {
  declare module.exports: $Exports<'codemirror/addon/scroll/simplescrollbars'>;
}
declare module 'codemirror/addon/search/jump-to-line.js' {
  declare module.exports: $Exports<'codemirror/addon/search/jump-to-line'>;
}
declare module 'codemirror/addon/search/match-highlighter.js' {
  declare module.exports: $Exports<'codemirror/addon/search/match-highlighter'>;
}
declare module 'codemirror/addon/search/matchesonscrollbar.js' {
  declare module.exports: $Exports<'codemirror/addon/search/matchesonscrollbar'>;
}
declare module 'codemirror/addon/search/search.js' {
  declare module.exports: $Exports<'codemirror/addon/search/search'>;
}
declare module 'codemirror/addon/search/searchcursor.js' {
  declare module.exports: $Exports<'codemirror/addon/search/searchcursor'>;
}
declare module 'codemirror/addon/selection/active-line.js' {
  declare module.exports: $Exports<'codemirror/addon/selection/active-line'>;
}
declare module 'codemirror/addon/selection/mark-selection.js' {
  declare module.exports: $Exports<'codemirror/addon/selection/mark-selection'>;
}
declare module 'codemirror/addon/selection/selection-pointer.js' {
  declare module.exports: $Exports<'codemirror/addon/selection/selection-pointer'>;
}
declare module 'codemirror/addon/tern/tern.js' {
  declare module.exports: $Exports<'codemirror/addon/tern/tern'>;
}
declare module 'codemirror/addon/tern/worker.js' {
  declare module.exports: $Exports<'codemirror/addon/tern/worker'>;
}
declare module 'codemirror/addon/wrap/hardwrap.js' {
  declare module.exports: $Exports<'codemirror/addon/wrap/hardwrap'>;
}
declare module 'codemirror/keymap/emacs.js' {
  declare module.exports: $Exports<'codemirror/keymap/emacs'>;
}
declare module 'codemirror/keymap/sublime.js' {
  declare module.exports: $Exports<'codemirror/keymap/sublime'>;
}
declare module 'codemirror/keymap/vim.js' {
  declare module.exports: $Exports<'codemirror/keymap/vim'>;
}
declare module 'codemirror/lib/codemirror.js' {
  declare module.exports: $Exports<'codemirror/lib/codemirror'>;
}
declare module 'codemirror/mode/apl/apl.js' {
  declare module.exports: $Exports<'codemirror/mode/apl/apl'>;
}
declare module 'codemirror/mode/asciiarmor/asciiarmor.js' {
  declare module.exports: $Exports<'codemirror/mode/asciiarmor/asciiarmor'>;
}
declare module 'codemirror/mode/asn.1/asn.1.js' {
  declare module.exports: $Exports<'codemirror/mode/asn.1/asn.1'>;
}
declare module 'codemirror/mode/asterisk/asterisk.js' {
  declare module.exports: $Exports<'codemirror/mode/asterisk/asterisk'>;
}
declare module 'codemirror/mode/brainfuck/brainfuck.js' {
  declare module.exports: $Exports<'codemirror/mode/brainfuck/brainfuck'>;
}
declare module 'codemirror/mode/clike/clike.js' {
  declare module.exports: $Exports<'codemirror/mode/clike/clike'>;
}
declare module 'codemirror/mode/clojure/clojure.js' {
  declare module.exports: $Exports<'codemirror/mode/clojure/clojure'>;
}
declare module 'codemirror/mode/cmake/cmake.js' {
  declare module.exports: $Exports<'codemirror/mode/cmake/cmake'>;
}
declare module 'codemirror/mode/cobol/cobol.js' {
  declare module.exports: $Exports<'codemirror/mode/cobol/cobol'>;
}
declare module 'codemirror/mode/coffeescript/coffeescript.js' {
  declare module.exports: $Exports<'codemirror/mode/coffeescript/coffeescript'>;
}
declare module 'codemirror/mode/commonlisp/commonlisp.js' {
  declare module.exports: $Exports<'codemirror/mode/commonlisp/commonlisp'>;
}
declare module 'codemirror/mode/crystal/crystal.js' {
  declare module.exports: $Exports<'codemirror/mode/crystal/crystal'>;
}
declare module 'codemirror/mode/css/css.js' {
  declare module.exports: $Exports<'codemirror/mode/css/css'>;
}
declare module 'codemirror/mode/cypher/cypher.js' {
  declare module.exports: $Exports<'codemirror/mode/cypher/cypher'>;
}
declare module 'codemirror/mode/d/d.js' {
  declare module.exports: $Exports<'codemirror/mode/d/d'>;
}
declare module 'codemirror/mode/dart/dart.js' {
  declare module.exports: $Exports<'codemirror/mode/dart/dart'>;
}
declare module 'codemirror/mode/diff/diff.js' {
  declare module.exports: $Exports<'codemirror/mode/diff/diff'>;
}
declare module 'codemirror/mode/django/django.js' {
  declare module.exports: $Exports<'codemirror/mode/django/django'>;
}
declare module 'codemirror/mode/dockerfile/dockerfile.js' {
  declare module.exports: $Exports<'codemirror/mode/dockerfile/dockerfile'>;
}
declare module 'codemirror/mode/dtd/dtd.js' {
  declare module.exports: $Exports<'codemirror/mode/dtd/dtd'>;
}
declare module 'codemirror/mode/dylan/dylan.js' {
  declare module.exports: $Exports<'codemirror/mode/dylan/dylan'>;
}
declare module 'codemirror/mode/ebnf/ebnf.js' {
  declare module.exports: $Exports<'codemirror/mode/ebnf/ebnf'>;
}
declare module 'codemirror/mode/ecl/ecl.js' {
  declare module.exports: $Exports<'codemirror/mode/ecl/ecl'>;
}
declare module 'codemirror/mode/eiffel/eiffel.js' {
  declare module.exports: $Exports<'codemirror/mode/eiffel/eiffel'>;
}
declare module 'codemirror/mode/elm/elm.js' {
  declare module.exports: $Exports<'codemirror/mode/elm/elm'>;
}
declare module 'codemirror/mode/erlang/erlang.js' {
  declare module.exports: $Exports<'codemirror/mode/erlang/erlang'>;
}
declare module 'codemirror/mode/factor/factor.js' {
  declare module.exports: $Exports<'codemirror/mode/factor/factor'>;
}
declare module 'codemirror/mode/fcl/fcl.js' {
  declare module.exports: $Exports<'codemirror/mode/fcl/fcl'>;
}
declare module 'codemirror/mode/forth/forth.js' {
  declare module.exports: $Exports<'codemirror/mode/forth/forth'>;
}
declare module 'codemirror/mode/fortran/fortran.js' {
  declare module.exports: $Exports<'codemirror/mode/fortran/fortran'>;
}
declare module 'codemirror/mode/gas/gas.js' {
  declare module.exports: $Exports<'codemirror/mode/gas/gas'>;
}
declare module 'codemirror/mode/gfm/gfm.js' {
  declare module.exports: $Exports<'codemirror/mode/gfm/gfm'>;
}
declare module 'codemirror/mode/gherkin/gherkin.js' {
  declare module.exports: $Exports<'codemirror/mode/gherkin/gherkin'>;
}
declare module 'codemirror/mode/go/go.js' {
  declare module.exports: $Exports<'codemirror/mode/go/go'>;
}
declare module 'codemirror/mode/groovy/groovy.js' {
  declare module.exports: $Exports<'codemirror/mode/groovy/groovy'>;
}
declare module 'codemirror/mode/haml/haml.js' {
  declare module.exports: $Exports<'codemirror/mode/haml/haml'>;
}
declare module 'codemirror/mode/handlebars/handlebars.js' {
  declare module.exports: $Exports<'codemirror/mode/handlebars/handlebars'>;
}
declare module 'codemirror/mode/haskell-literate/haskell-literate.js' {
  declare module.exports: $Exports<'codemirror/mode/haskell-literate/haskell-literate'>;
}
declare module 'codemirror/mode/haskell/haskell.js' {
  declare module.exports: $Exports<'codemirror/mode/haskell/haskell'>;
}
declare module 'codemirror/mode/haxe/haxe.js' {
  declare module.exports: $Exports<'codemirror/mode/haxe/haxe'>;
}
declare module 'codemirror/mode/htmlembedded/htmlembedded.js' {
  declare module.exports: $Exports<'codemirror/mode/htmlembedded/htmlembedded'>;
}
declare module 'codemirror/mode/htmlmixed/htmlmixed.js' {
  declare module.exports: $Exports<'codemirror/mode/htmlmixed/htmlmixed'>;
}
declare module 'codemirror/mode/http/http.js' {
  declare module.exports: $Exports<'codemirror/mode/http/http'>;
}
declare module 'codemirror/mode/idl/idl.js' {
  declare module.exports: $Exports<'codemirror/mode/idl/idl'>;
}
declare module 'codemirror/mode/javascript/javascript.js' {
  declare module.exports: $Exports<'codemirror/mode/javascript/javascript'>;
}
declare module 'codemirror/mode/jinja2/jinja2.js' {
  declare module.exports: $Exports<'codemirror/mode/jinja2/jinja2'>;
}
declare module 'codemirror/mode/jsx/jsx.js' {
  declare module.exports: $Exports<'codemirror/mode/jsx/jsx'>;
}
declare module 'codemirror/mode/julia/julia.js' {
  declare module.exports: $Exports<'codemirror/mode/julia/julia'>;
}
declare module 'codemirror/mode/livescript/livescript.js' {
  declare module.exports: $Exports<'codemirror/mode/livescript/livescript'>;
}
declare module 'codemirror/mode/lua/lua.js' {
  declare module.exports: $Exports<'codemirror/mode/lua/lua'>;
}
declare module 'codemirror/mode/markdown/markdown.js' {
  declare module.exports: $Exports<'codemirror/mode/markdown/markdown'>;
}
declare module 'codemirror/mode/mathematica/mathematica.js' {
  declare module.exports: $Exports<'codemirror/mode/mathematica/mathematica'>;
}
declare module 'codemirror/mode/mbox/mbox.js' {
  declare module.exports: $Exports<'codemirror/mode/mbox/mbox'>;
}
declare module 'codemirror/mode/meta.js' {
  declare module.exports: $Exports<'codemirror/mode/meta'>;
}
declare module 'codemirror/mode/mirc/mirc.js' {
  declare module.exports: $Exports<'codemirror/mode/mirc/mirc'>;
}
declare module 'codemirror/mode/mllike/mllike.js' {
  declare module.exports: $Exports<'codemirror/mode/mllike/mllike'>;
}
declare module 'codemirror/mode/modelica/modelica.js' {
  declare module.exports: $Exports<'codemirror/mode/modelica/modelica'>;
}
declare module 'codemirror/mode/mscgen/mscgen.js' {
  declare module.exports: $Exports<'codemirror/mode/mscgen/mscgen'>;
}
declare module 'codemirror/mode/mumps/mumps.js' {
  declare module.exports: $Exports<'codemirror/mode/mumps/mumps'>;
}
declare module 'codemirror/mode/nginx/nginx.js' {
  declare module.exports: $Exports<'codemirror/mode/nginx/nginx'>;
}
declare module 'codemirror/mode/nsis/nsis.js' {
  declare module.exports: $Exports<'codemirror/mode/nsis/nsis'>;
}
declare module 'codemirror/mode/ntriples/ntriples.js' {
  declare module.exports: $Exports<'codemirror/mode/ntriples/ntriples'>;
}
declare module 'codemirror/mode/octave/octave.js' {
  declare module.exports: $Exports<'codemirror/mode/octave/octave'>;
}
declare module 'codemirror/mode/oz/oz.js' {
  declare module.exports: $Exports<'codemirror/mode/oz/oz'>;
}
declare module 'codemirror/mode/pascal/pascal.js' {
  declare module.exports: $Exports<'codemirror/mode/pascal/pascal'>;
}
declare module 'codemirror/mode/pegjs/pegjs.js' {
  declare module.exports: $Exports<'codemirror/mode/pegjs/pegjs'>;
}
declare module 'codemirror/mode/perl/perl.js' {
  declare module.exports: $Exports<'codemirror/mode/perl/perl'>;
}
declare module 'codemirror/mode/php/php.js' {
  declare module.exports: $Exports<'codemirror/mode/php/php'>;
}
declare module 'codemirror/mode/pig/pig.js' {
  declare module.exports: $Exports<'codemirror/mode/pig/pig'>;
}
declare module 'codemirror/mode/powershell/powershell.js' {
  declare module.exports: $Exports<'codemirror/mode/powershell/powershell'>;
}
declare module 'codemirror/mode/properties/properties.js' {
  declare module.exports: $Exports<'codemirror/mode/properties/properties'>;
}
declare module 'codemirror/mode/protobuf/protobuf.js' {
  declare module.exports: $Exports<'codemirror/mode/protobuf/protobuf'>;
}
declare module 'codemirror/mode/pug/pug.js' {
  declare module.exports: $Exports<'codemirror/mode/pug/pug'>;
}
declare module 'codemirror/mode/puppet/puppet.js' {
  declare module.exports: $Exports<'codemirror/mode/puppet/puppet'>;
}
declare module 'codemirror/mode/python/python.js' {
  declare module.exports: $Exports<'codemirror/mode/python/python'>;
}
declare module 'codemirror/mode/q/q.js' {
  declare module.exports: $Exports<'codemirror/mode/q/q'>;
}
declare module 'codemirror/mode/r/r.js' {
  declare module.exports: $Exports<'codemirror/mode/r/r'>;
}
declare module 'codemirror/mode/rpm/rpm.js' {
  declare module.exports: $Exports<'codemirror/mode/rpm/rpm'>;
}
declare module 'codemirror/mode/rst/rst.js' {
  declare module.exports: $Exports<'codemirror/mode/rst/rst'>;
}
declare module 'codemirror/mode/ruby/ruby.js' {
  declare module.exports: $Exports<'codemirror/mode/ruby/ruby'>;
}
declare module 'codemirror/mode/rust/rust.js' {
  declare module.exports: $Exports<'codemirror/mode/rust/rust'>;
}
declare module 'codemirror/mode/sas/sas.js' {
  declare module.exports: $Exports<'codemirror/mode/sas/sas'>;
}
declare module 'codemirror/mode/sass/sass.js' {
  declare module.exports: $Exports<'codemirror/mode/sass/sass'>;
}
declare module 'codemirror/mode/scheme/scheme.js' {
  declare module.exports: $Exports<'codemirror/mode/scheme/scheme'>;
}
declare module 'codemirror/mode/shell/shell.js' {
  declare module.exports: $Exports<'codemirror/mode/shell/shell'>;
}
declare module 'codemirror/mode/sieve/sieve.js' {
  declare module.exports: $Exports<'codemirror/mode/sieve/sieve'>;
}
declare module 'codemirror/mode/slim/slim.js' {
  declare module.exports: $Exports<'codemirror/mode/slim/slim'>;
}
declare module 'codemirror/mode/smalltalk/smalltalk.js' {
  declare module.exports: $Exports<'codemirror/mode/smalltalk/smalltalk'>;
}
declare module 'codemirror/mode/smarty/smarty.js' {
  declare module.exports: $Exports<'codemirror/mode/smarty/smarty'>;
}
declare module 'codemirror/mode/solr/solr.js' {
  declare module.exports: $Exports<'codemirror/mode/solr/solr'>;
}
declare module 'codemirror/mode/soy/soy.js' {
  declare module.exports: $Exports<'codemirror/mode/soy/soy'>;
}
declare module 'codemirror/mode/sparql/sparql.js' {
  declare module.exports: $Exports<'codemirror/mode/sparql/sparql'>;
}
declare module 'codemirror/mode/spreadsheet/spreadsheet.js' {
  declare module.exports: $Exports<'codemirror/mode/spreadsheet/spreadsheet'>;
}
declare module 'codemirror/mode/sql/sql.js' {
  declare module.exports: $Exports<'codemirror/mode/sql/sql'>;
}
declare module 'codemirror/mode/stex/stex.js' {
  declare module.exports: $Exports<'codemirror/mode/stex/stex'>;
}
declare module 'codemirror/mode/stylus/stylus.js' {
  declare module.exports: $Exports<'codemirror/mode/stylus/stylus'>;
}
declare module 'codemirror/mode/swift/swift.js' {
  declare module.exports: $Exports<'codemirror/mode/swift/swift'>;
}
declare module 'codemirror/mode/tcl/tcl.js' {
  declare module.exports: $Exports<'codemirror/mode/tcl/tcl'>;
}
declare module 'codemirror/mode/textile/textile.js' {
  declare module.exports: $Exports<'codemirror/mode/textile/textile'>;
}
declare module 'codemirror/mode/tiddlywiki/tiddlywiki.js' {
  declare module.exports: $Exports<'codemirror/mode/tiddlywiki/tiddlywiki'>;
}
declare module 'codemirror/mode/tiki/tiki.js' {
  declare module.exports: $Exports<'codemirror/mode/tiki/tiki'>;
}
declare module 'codemirror/mode/toml/toml.js' {
  declare module.exports: $Exports<'codemirror/mode/toml/toml'>;
}
declare module 'codemirror/mode/tornado/tornado.js' {
  declare module.exports: $Exports<'codemirror/mode/tornado/tornado'>;
}
declare module 'codemirror/mode/troff/troff.js' {
  declare module.exports: $Exports<'codemirror/mode/troff/troff'>;
}
declare module 'codemirror/mode/ttcn-cfg/ttcn-cfg.js' {
  declare module.exports: $Exports<'codemirror/mode/ttcn-cfg/ttcn-cfg'>;
}
declare module 'codemirror/mode/ttcn/ttcn.js' {
  declare module.exports: $Exports<'codemirror/mode/ttcn/ttcn'>;
}
declare module 'codemirror/mode/turtle/turtle.js' {
  declare module.exports: $Exports<'codemirror/mode/turtle/turtle'>;
}
declare module 'codemirror/mode/twig/twig.js' {
  declare module.exports: $Exports<'codemirror/mode/twig/twig'>;
}
declare module 'codemirror/mode/vb/vb.js' {
  declare module.exports: $Exports<'codemirror/mode/vb/vb'>;
}
declare module 'codemirror/mode/vbscript/vbscript.js' {
  declare module.exports: $Exports<'codemirror/mode/vbscript/vbscript'>;
}
declare module 'codemirror/mode/velocity/velocity.js' {
  declare module.exports: $Exports<'codemirror/mode/velocity/velocity'>;
}
declare module 'codemirror/mode/verilog/verilog.js' {
  declare module.exports: $Exports<'codemirror/mode/verilog/verilog'>;
}
declare module 'codemirror/mode/vhdl/vhdl.js' {
  declare module.exports: $Exports<'codemirror/mode/vhdl/vhdl'>;
}
declare module 'codemirror/mode/vue/vue.js' {
  declare module.exports: $Exports<'codemirror/mode/vue/vue'>;
}
declare module 'codemirror/mode/webidl/webidl.js' {
  declare module.exports: $Exports<'codemirror/mode/webidl/webidl'>;
}
declare module 'codemirror/mode/xml/xml.js' {
  declare module.exports: $Exports<'codemirror/mode/xml/xml'>;
}
declare module 'codemirror/mode/xquery/xquery.js' {
  declare module.exports: $Exports<'codemirror/mode/xquery/xquery'>;
}
declare module 'codemirror/mode/yacas/yacas.js' {
  declare module.exports: $Exports<'codemirror/mode/yacas/yacas'>;
}
declare module 'codemirror/mode/yaml-frontmatter/yaml-frontmatter.js' {
  declare module.exports: $Exports<'codemirror/mode/yaml-frontmatter/yaml-frontmatter'>;
}
declare module 'codemirror/mode/yaml/yaml.js' {
  declare module.exports: $Exports<'codemirror/mode/yaml/yaml'>;
}
declare module 'codemirror/mode/z80/z80.js' {
  declare module.exports: $Exports<'codemirror/mode/z80/z80'>;
}
declare module 'codemirror/rollup.config.js' {
  declare module.exports: $Exports<'codemirror/rollup.config'>;
}
declare module 'codemirror/src/codemirror.js' {
  declare module.exports: $Exports<'codemirror/src/codemirror'>;
}
declare module 'codemirror/src/display/Display.js' {
  declare module.exports: $Exports<'codemirror/src/display/Display'>;
}
declare module 'codemirror/src/display/focus.js' {
  declare module.exports: $Exports<'codemirror/src/display/focus'>;
}
declare module 'codemirror/src/display/gutters.js' {
  declare module.exports: $Exports<'codemirror/src/display/gutters'>;
}
declare module 'codemirror/src/display/highlight_worker.js' {
  declare module.exports: $Exports<'codemirror/src/display/highlight_worker'>;
}
declare module 'codemirror/src/display/line_numbers.js' {
  declare module.exports: $Exports<'codemirror/src/display/line_numbers'>;
}
declare module 'codemirror/src/display/mode_state.js' {
  declare module.exports: $Exports<'codemirror/src/display/mode_state'>;
}
declare module 'codemirror/src/display/operations.js' {
  declare module.exports: $Exports<'codemirror/src/display/operations'>;
}
declare module 'codemirror/src/display/scroll_events.js' {
  declare module.exports: $Exports<'codemirror/src/display/scroll_events'>;
}
declare module 'codemirror/src/display/scrollbars.js' {
  declare module.exports: $Exports<'codemirror/src/display/scrollbars'>;
}
declare module 'codemirror/src/display/scrolling.js' {
  declare module.exports: $Exports<'codemirror/src/display/scrolling'>;
}
declare module 'codemirror/src/display/selection.js' {
  declare module.exports: $Exports<'codemirror/src/display/selection'>;
}
declare module 'codemirror/src/display/update_display.js' {
  declare module.exports: $Exports<'codemirror/src/display/update_display'>;
}
declare module 'codemirror/src/display/update_line.js' {
  declare module.exports: $Exports<'codemirror/src/display/update_line'>;
}
declare module 'codemirror/src/display/update_lines.js' {
  declare module.exports: $Exports<'codemirror/src/display/update_lines'>;
}
declare module 'codemirror/src/display/view_tracking.js' {
  declare module.exports: $Exports<'codemirror/src/display/view_tracking'>;
}
declare module 'codemirror/src/edit/CodeMirror.js' {
  declare module.exports: $Exports<'codemirror/src/edit/CodeMirror'>;
}
declare module 'codemirror/src/edit/commands.js' {
  declare module.exports: $Exports<'codemirror/src/edit/commands'>;
}
declare module 'codemirror/src/edit/deleteNearSelection.js' {
  declare module.exports: $Exports<'codemirror/src/edit/deleteNearSelection'>;
}
declare module 'codemirror/src/edit/drop_events.js' {
  declare module.exports: $Exports<'codemirror/src/edit/drop_events'>;
}
declare module 'codemirror/src/edit/fromTextArea.js' {
  declare module.exports: $Exports<'codemirror/src/edit/fromTextArea'>;
}
declare module 'codemirror/src/edit/global_events.js' {
  declare module.exports: $Exports<'codemirror/src/edit/global_events'>;
}
declare module 'codemirror/src/edit/key_events.js' {
  declare module.exports: $Exports<'codemirror/src/edit/key_events'>;
}
declare module 'codemirror/src/edit/legacy.js' {
  declare module.exports: $Exports<'codemirror/src/edit/legacy'>;
}
declare module 'codemirror/src/edit/main.js' {
  declare module.exports: $Exports<'codemirror/src/edit/main'>;
}
declare module 'codemirror/src/edit/methods.js' {
  declare module.exports: $Exports<'codemirror/src/edit/methods'>;
}
declare module 'codemirror/src/edit/mouse_events.js' {
  declare module.exports: $Exports<'codemirror/src/edit/mouse_events'>;
}
declare module 'codemirror/src/edit/options.js' {
  declare module.exports: $Exports<'codemirror/src/edit/options'>;
}
declare module 'codemirror/src/edit/utils.js' {
  declare module.exports: $Exports<'codemirror/src/edit/utils'>;
}
declare module 'codemirror/src/input/ContentEditableInput.js' {
  declare module.exports: $Exports<'codemirror/src/input/ContentEditableInput'>;
}
declare module 'codemirror/src/input/indent.js' {
  declare module.exports: $Exports<'codemirror/src/input/indent'>;
}
declare module 'codemirror/src/input/input.js' {
  declare module.exports: $Exports<'codemirror/src/input/input'>;
}
declare module 'codemirror/src/input/keymap.js' {
  declare module.exports: $Exports<'codemirror/src/input/keymap'>;
}
declare module 'codemirror/src/input/keynames.js' {
  declare module.exports: $Exports<'codemirror/src/input/keynames'>;
}
declare module 'codemirror/src/input/movement.js' {
  declare module.exports: $Exports<'codemirror/src/input/movement'>;
}
declare module 'codemirror/src/input/TextareaInput.js' {
  declare module.exports: $Exports<'codemirror/src/input/TextareaInput'>;
}
declare module 'codemirror/src/line/highlight.js' {
  declare module.exports: $Exports<'codemirror/src/line/highlight'>;
}
declare module 'codemirror/src/line/line_data.js' {
  declare module.exports: $Exports<'codemirror/src/line/line_data'>;
}
declare module 'codemirror/src/line/pos.js' {
  declare module.exports: $Exports<'codemirror/src/line/pos'>;
}
declare module 'codemirror/src/line/saw_special_spans.js' {
  declare module.exports: $Exports<'codemirror/src/line/saw_special_spans'>;
}
declare module 'codemirror/src/line/spans.js' {
  declare module.exports: $Exports<'codemirror/src/line/spans'>;
}
declare module 'codemirror/src/line/utils_line.js' {
  declare module.exports: $Exports<'codemirror/src/line/utils_line'>;
}
declare module 'codemirror/src/measurement/position_measurement.js' {
  declare module.exports: $Exports<'codemirror/src/measurement/position_measurement'>;
}
declare module 'codemirror/src/measurement/widgets.js' {
  declare module.exports: $Exports<'codemirror/src/measurement/widgets'>;
}
declare module 'codemirror/src/model/change_measurement.js' {
  declare module.exports: $Exports<'codemirror/src/model/change_measurement'>;
}
declare module 'codemirror/src/model/changes.js' {
  declare module.exports: $Exports<'codemirror/src/model/changes'>;
}
declare module 'codemirror/src/model/chunk.js' {
  declare module.exports: $Exports<'codemirror/src/model/chunk'>;
}
declare module 'codemirror/src/model/Doc.js' {
  declare module.exports: $Exports<'codemirror/src/model/Doc'>;
}
declare module 'codemirror/src/model/document_data.js' {
  declare module.exports: $Exports<'codemirror/src/model/document_data'>;
}
declare module 'codemirror/src/model/history.js' {
  declare module.exports: $Exports<'codemirror/src/model/history'>;
}
declare module 'codemirror/src/model/line_widget.js' {
  declare module.exports: $Exports<'codemirror/src/model/line_widget'>;
}
declare module 'codemirror/src/model/mark_text.js' {
  declare module.exports: $Exports<'codemirror/src/model/mark_text'>;
}
declare module 'codemirror/src/model/selection_updates.js' {
  declare module.exports: $Exports<'codemirror/src/model/selection_updates'>;
}
declare module 'codemirror/src/model/selection.js' {
  declare module.exports: $Exports<'codemirror/src/model/selection'>;
}
declare module 'codemirror/src/modes.js' {
  declare module.exports: $Exports<'codemirror/src/modes'>;
}
declare module 'codemirror/src/util/bidi.js' {
  declare module.exports: $Exports<'codemirror/src/util/bidi'>;
}
declare module 'codemirror/src/util/browser.js' {
  declare module.exports: $Exports<'codemirror/src/util/browser'>;
}
declare module 'codemirror/src/util/dom.js' {
  declare module.exports: $Exports<'codemirror/src/util/dom'>;
}
declare module 'codemirror/src/util/event.js' {
  declare module.exports: $Exports<'codemirror/src/util/event'>;
}
declare module 'codemirror/src/util/feature_detection.js' {
  declare module.exports: $Exports<'codemirror/src/util/feature_detection'>;
}
declare module 'codemirror/src/util/misc.js' {
  declare module.exports: $Exports<'codemirror/src/util/misc'>;
}
declare module 'codemirror/src/util/operation_group.js' {
  declare module.exports: $Exports<'codemirror/src/util/operation_group'>;
}
declare module 'codemirror/src/util/StringStream.js' {
  declare module.exports: $Exports<'codemirror/src/util/StringStream'>;
}
