// flow-typed signature: 3d651fc79523c92efe95077d29cac82f
// flow-typed version: <<STUB>>/dateformat_v3.0.3/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dateformat'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dateformat' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dateformat/lib/dateformat' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dateformat/lib/dateformat.js' {
  declare module.exports: $Exports<'dateformat/lib/dateformat'>;
}
