// flow-typed signature: ac858859a846498c06179ada0c8b78a1
// flow-typed version: <<STUB>>/deep-equal_v^1.0.1/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'deep-equal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'deep-equal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'deep-equal/example/cmp' {
  declare module.exports: any;
}

declare module 'deep-equal/lib/is_arguments' {
  declare module.exports: any;
}

declare module 'deep-equal/lib/keys' {
  declare module.exports: any;
}

declare module 'deep-equal/test/cmp' {
  declare module.exports: any;
}

// Filename aliases
declare module 'deep-equal/example/cmp.js' {
  declare module.exports: $Exports<'deep-equal/example/cmp'>;
}
declare module 'deep-equal/index' {
  declare module.exports: $Exports<'deep-equal'>;
}
declare module 'deep-equal/index.js' {
  declare module.exports: $Exports<'deep-equal'>;
}
declare module 'deep-equal/lib/is_arguments.js' {
  declare module.exports: $Exports<'deep-equal/lib/is_arguments'>;
}
declare module 'deep-equal/lib/keys.js' {
  declare module.exports: $Exports<'deep-equal/lib/keys'>;
}
declare module 'deep-equal/test/cmp.js' {
  declare module.exports: $Exports<'deep-equal/test/cmp'>;
}
