// flow-typed signature: bcecc715564737f1856994b80c3fff42
// flow-typed version: <<STUB>>/eslint-plugin-prettify_v^1.0.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-prettify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-prettify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-prettify/no-styles' {
  declare module.exports: any;
}

declare module 'eslint-plugin-prettify/rule' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-prettify/index' {
  declare module.exports: $Exports<'eslint-plugin-prettify'>;
}
declare module 'eslint-plugin-prettify/index.js' {
  declare module.exports: $Exports<'eslint-plugin-prettify'>;
}
declare module 'eslint-plugin-prettify/no-styles.js' {
  declare module.exports: $Exports<'eslint-plugin-prettify/no-styles'>;
}
declare module 'eslint-plugin-prettify/rule.js' {
  declare module.exports: $Exports<'eslint-plugin-prettify/rule'>;
}
