// flow-typed signature: 7d9003fbbea8ad826e49acce81fe56fb
// flow-typed version: <<STUB>>/expand-tilde_v2.0.2/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expand-tilde'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expand-tilde' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'expand-tilde/index' {
  declare module.exports: $Exports<'expand-tilde'>;
}
declare module 'expand-tilde/index.js' {
  declare module.exports: $Exports<'expand-tilde'>;
}
