// flow-typed signature: 6187fdc45c9567c2e88b8d4399bc1300
// flow-typed version: <<STUB>>/google-palette_vlatest/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'google-palette'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'google-palette' {
  declare module.exports: any;
}
