// flow-typed signature: 69ddad32e70eb9e1eb79e7ce2017117b
// flow-typed version: <<STUB>>/graphiql_v0.11.10/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphiql'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphiql' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphiql/dist/components/DocExplorer' {
  declare module.exports: any;
}

declare module 'graphiql/dist/components/DocExplorer/Argument' {
  declare module.exports: any;
}

declare module 'graphiql/dist/components/DocExplorer/DefaultValue' {
  declare module.exports: any;
}

declare module 'graphiql/dist/components/DocExplorer/FieldDoc' {
  declare module.exports: any;
}

declare module 'graphiql/dist/components/DocExplorer/MarkdownContent' {
  declare module.exports: any;
}

declare module 'graphiql/dist/components/DocExplorer/SchemaDoc' {
  declare module.exports: any;
}

declare module 'graphiql/dist/components/DocExplorer/SearchBox' {
  declare module.exports: any;
}

declare module 'graphiql/dist/components/DocExplorer/SearchResults' {
  declare module.exports: any;
}

declare module 'graphiql/dist/components/DocExplorer/TypeDoc' {
  declare module.exports: any;
}

declare module 'graphiql/dist/components/DocExplorer/TypeLink' {
  declare module.exports: any;
}

declare module 'graphiql/dist/components/ExecuteButton' {
  declare module.exports: any;
}

declare module 'graphiql/dist/components/GraphiQL' {
  declare module.exports: any;
}

declare module 'graphiql/dist/components/HistoryQuery' {
  declare module.exports: any;
}

declare module 'graphiql/dist/components/QueryEditor' {
  declare module.exports: any;
}

declare module 'graphiql/dist/components/QueryHistory' {
  declare module.exports: any;
}

declare module 'graphiql/dist/components/ResultViewer' {
  declare module.exports: any;
}

declare module 'graphiql/dist/components/ToolbarButton' {
  declare module.exports: any;
}

declare module 'graphiql/dist/components/ToolbarGroup' {
  declare module.exports: any;
}

declare module 'graphiql/dist/components/ToolbarMenu' {
  declare module.exports: any;
}

declare module 'graphiql/dist/components/ToolbarSelect' {
  declare module.exports: any;
}

declare module 'graphiql/dist/components/VariableEditor' {
  declare module.exports: any;
}

declare module 'graphiql/dist/index' {
  declare module.exports: any;
}

declare module 'graphiql/dist/utility/CodeMirrorSizer' {
  declare module.exports: any;
}

declare module 'graphiql/dist/utility/debounce' {
  declare module.exports: any;
}

declare module 'graphiql/dist/utility/elementPosition' {
  declare module.exports: any;
}

declare module 'graphiql/dist/utility/fillLeafs' {
  declare module.exports: any;
}

declare module 'graphiql/dist/utility/find' {
  declare module.exports: any;
}

declare module 'graphiql/dist/utility/getQueryFacts' {
  declare module.exports: any;
}

declare module 'graphiql/dist/utility/getSelectedOperationName' {
  declare module.exports: any;
}

declare module 'graphiql/dist/utility/introspectionQueries' {
  declare module.exports: any;
}

declare module 'graphiql/dist/utility/normalizeWhitespace' {
  declare module.exports: any;
}

declare module 'graphiql/dist/utility/onHasCompletion' {
  declare module.exports: any;
}

declare module 'graphiql/dist/utility/QueryStore' {
  declare module.exports: any;
}

declare module 'graphiql/dist/utility/StorageAPI' {
  declare module.exports: any;
}

declare module 'graphiql/graphiql' {
  declare module.exports: any;
}

declare module 'graphiql/graphiql.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphiql/dist/components/DocExplorer.js' {
  declare module.exports: $Exports<'graphiql/dist/components/DocExplorer'>;
}
declare module 'graphiql/dist/components/DocExplorer/Argument.js' {
  declare module.exports: $Exports<'graphiql/dist/components/DocExplorer/Argument'>;
}
declare module 'graphiql/dist/components/DocExplorer/DefaultValue.js' {
  declare module.exports: $Exports<'graphiql/dist/components/DocExplorer/DefaultValue'>;
}
declare module 'graphiql/dist/components/DocExplorer/FieldDoc.js' {
  declare module.exports: $Exports<'graphiql/dist/components/DocExplorer/FieldDoc'>;
}
declare module 'graphiql/dist/components/DocExplorer/MarkdownContent.js' {
  declare module.exports: $Exports<'graphiql/dist/components/DocExplorer/MarkdownContent'>;
}
declare module 'graphiql/dist/components/DocExplorer/SchemaDoc.js' {
  declare module.exports: $Exports<'graphiql/dist/components/DocExplorer/SchemaDoc'>;
}
declare module 'graphiql/dist/components/DocExplorer/SearchBox.js' {
  declare module.exports: $Exports<'graphiql/dist/components/DocExplorer/SearchBox'>;
}
declare module 'graphiql/dist/components/DocExplorer/SearchResults.js' {
  declare module.exports: $Exports<'graphiql/dist/components/DocExplorer/SearchResults'>;
}
declare module 'graphiql/dist/components/DocExplorer/TypeDoc.js' {
  declare module.exports: $Exports<'graphiql/dist/components/DocExplorer/TypeDoc'>;
}
declare module 'graphiql/dist/components/DocExplorer/TypeLink.js' {
  declare module.exports: $Exports<'graphiql/dist/components/DocExplorer/TypeLink'>;
}
declare module 'graphiql/dist/components/ExecuteButton.js' {
  declare module.exports: $Exports<'graphiql/dist/components/ExecuteButton'>;
}
declare module 'graphiql/dist/components/GraphiQL.js' {
  declare module.exports: $Exports<'graphiql/dist/components/GraphiQL'>;
}
declare module 'graphiql/dist/components/HistoryQuery.js' {
  declare module.exports: $Exports<'graphiql/dist/components/HistoryQuery'>;
}
declare module 'graphiql/dist/components/QueryEditor.js' {
  declare module.exports: $Exports<'graphiql/dist/components/QueryEditor'>;
}
declare module 'graphiql/dist/components/QueryHistory.js' {
  declare module.exports: $Exports<'graphiql/dist/components/QueryHistory'>;
}
declare module 'graphiql/dist/components/ResultViewer.js' {
  declare module.exports: $Exports<'graphiql/dist/components/ResultViewer'>;
}
declare module 'graphiql/dist/components/ToolbarButton.js' {
  declare module.exports: $Exports<'graphiql/dist/components/ToolbarButton'>;
}
declare module 'graphiql/dist/components/ToolbarGroup.js' {
  declare module.exports: $Exports<'graphiql/dist/components/ToolbarGroup'>;
}
declare module 'graphiql/dist/components/ToolbarMenu.js' {
  declare module.exports: $Exports<'graphiql/dist/components/ToolbarMenu'>;
}
declare module 'graphiql/dist/components/ToolbarSelect.js' {
  declare module.exports: $Exports<'graphiql/dist/components/ToolbarSelect'>;
}
declare module 'graphiql/dist/components/VariableEditor.js' {
  declare module.exports: $Exports<'graphiql/dist/components/VariableEditor'>;
}
declare module 'graphiql/dist/index.js' {
  declare module.exports: $Exports<'graphiql/dist/index'>;
}
declare module 'graphiql/dist/utility/CodeMirrorSizer.js' {
  declare module.exports: $Exports<'graphiql/dist/utility/CodeMirrorSizer'>;
}
declare module 'graphiql/dist/utility/debounce.js' {
  declare module.exports: $Exports<'graphiql/dist/utility/debounce'>;
}
declare module 'graphiql/dist/utility/elementPosition.js' {
  declare module.exports: $Exports<'graphiql/dist/utility/elementPosition'>;
}
declare module 'graphiql/dist/utility/fillLeafs.js' {
  declare module.exports: $Exports<'graphiql/dist/utility/fillLeafs'>;
}
declare module 'graphiql/dist/utility/find.js' {
  declare module.exports: $Exports<'graphiql/dist/utility/find'>;
}
declare module 'graphiql/dist/utility/getQueryFacts.js' {
  declare module.exports: $Exports<'graphiql/dist/utility/getQueryFacts'>;
}
declare module 'graphiql/dist/utility/getSelectedOperationName.js' {
  declare module.exports: $Exports<'graphiql/dist/utility/getSelectedOperationName'>;
}
declare module 'graphiql/dist/utility/introspectionQueries.js' {
  declare module.exports: $Exports<'graphiql/dist/utility/introspectionQueries'>;
}
declare module 'graphiql/dist/utility/normalizeWhitespace.js' {
  declare module.exports: $Exports<'graphiql/dist/utility/normalizeWhitespace'>;
}
declare module 'graphiql/dist/utility/onHasCompletion.js' {
  declare module.exports: $Exports<'graphiql/dist/utility/onHasCompletion'>;
}
declare module 'graphiql/dist/utility/QueryStore.js' {
  declare module.exports: $Exports<'graphiql/dist/utility/QueryStore'>;
}
declare module 'graphiql/dist/utility/StorageAPI.js' {
  declare module.exports: $Exports<'graphiql/dist/utility/StorageAPI'>;
}
declare module 'graphiql/graphiql.js' {
  declare module.exports: $Exports<'graphiql/graphiql'>;
}
declare module 'graphiql/graphiql.min.js' {
  declare module.exports: $Exports<'graphiql/graphiql.min'>;
}
