// flow-typed signature: 0eceddcdb50aa9bf578c375a12ef9aad
// flow-typed version: <<STUB>>/lodash.memoize_v4.1.2/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.memoize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.memoize' {
  declare function memoize<T>(fn: T, resolver?: Function): T;
  declare export default typeof memoize;
}
