// flow-typed signature: 95241cb8305cb4cbda994a489dff963f
// flow-typed version: <<STUB>>/lodash.debounce_v4.0.8/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.debounce'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.debounce' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.debounce/index' {
  declare module.exports: $Exports<'lodash.debounce'>;
}
declare module 'lodash.debounce/index.js' {
  declare module.exports: $Exports<'lodash.debounce'>;
}
