// flow-typed signature: de535bf82f2186287df01b1d05ef7355
// flow-typed version: <<STUB>>/openssl-wrapper_v0.3.4/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'openssl-wrapper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'openssl-wrapper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'openssl-wrapper/lib/index' {
  declare module.exports: any;
}

declare module 'openssl-wrapper/src/index' {
  declare module.exports: any;
}

declare module 'openssl-wrapper/test/index.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'openssl-wrapper/lib/index.js' {
  declare module.exports: $Exports<'openssl-wrapper/lib/index'>;
}
declare module 'openssl-wrapper/src/index.js' {
  declare module.exports: $Exports<'openssl-wrapper/src/index'>;
}
declare module 'openssl-wrapper/test/index.spec.js' {
  declare module.exports: $Exports<'openssl-wrapper/test/index.spec'>;
}
