// flow-typed signature: cac2176ef31aded3d7080a130d8e79dc
// flow-typed version: <<STUB>>/prism-react-renderer_v^0.1.2/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prism-react-renderer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prism-react-renderer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prism-react-renderer/es/components/Highlight' {
  declare module.exports: any;
}

declare module 'prism-react-renderer/es/defaultProps' {
  declare module.exports: any;
}

declare module 'prism-react-renderer/es/index' {
  declare module.exports: any;
}

declare module 'prism-react-renderer/es/types' {
  declare module.exports: any;
}

declare module 'prism-react-renderer/es/utils/normalizeTokens' {
  declare module.exports: any;
}

declare module 'prism-react-renderer/es/utils/themeToDict' {
  declare module.exports: any;
}

declare module 'prism-react-renderer/es/vendor/prism/includeLangs' {
  declare module.exports: any;
}

declare module 'prism-react-renderer/es/vendor/prism/index' {
  declare module.exports: any;
}

declare module 'prism-react-renderer/es/vendor/prism/prism-core' {
  declare module.exports: any;
}

declare module 'prism-react-renderer/lib/components/Highlight' {
  declare module.exports: any;
}

declare module 'prism-react-renderer/lib/defaultProps' {
  declare module.exports: any;
}

declare module 'prism-react-renderer/lib/index' {
  declare module.exports: any;
}

declare module 'prism-react-renderer/lib/types' {
  declare module.exports: any;
}

declare module 'prism-react-renderer/lib/utils/normalizeTokens' {
  declare module.exports: any;
}

declare module 'prism-react-renderer/lib/utils/themeToDict' {
  declare module.exports: any;
}

declare module 'prism-react-renderer/lib/vendor/prism/includeLangs' {
  declare module.exports: any;
}

declare module 'prism-react-renderer/lib/vendor/prism/index' {
  declare module.exports: any;
}

declare module 'prism-react-renderer/lib/vendor/prism/prism-core' {
  declare module.exports: any;
}

declare module 'prism-react-renderer/themes/dracula' {
  declare module.exports: any;
}

declare module 'prism-react-renderer/themes/duotoneDark' {
  declare module.exports: any;
}

declare module 'prism-react-renderer/themes/duotoneLight' {
  declare module.exports: any;
}

declare module 'prism-react-renderer/themes/nightOwl' {
  declare module.exports: any;
}

declare module 'prism-react-renderer/themes/oceanicNext' {
  declare module.exports: any;
}

declare module 'prism-react-renderer/themes/ultramin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'prism-react-renderer/es/components/Highlight.js' {
  declare module.exports: $Exports<'prism-react-renderer/es/components/Highlight'>;
}
declare module 'prism-react-renderer/es/defaultProps.js' {
  declare module.exports: $Exports<'prism-react-renderer/es/defaultProps'>;
}
declare module 'prism-react-renderer/es/index.js' {
  declare module.exports: $Exports<'prism-react-renderer/es/index'>;
}
declare module 'prism-react-renderer/es/types.js' {
  declare module.exports: $Exports<'prism-react-renderer/es/types'>;
}
declare module 'prism-react-renderer/es/utils/normalizeTokens.js' {
  declare module.exports: $Exports<'prism-react-renderer/es/utils/normalizeTokens'>;
}
declare module 'prism-react-renderer/es/utils/themeToDict.js' {
  declare module.exports: $Exports<'prism-react-renderer/es/utils/themeToDict'>;
}
declare module 'prism-react-renderer/es/vendor/prism/includeLangs.js' {
  declare module.exports: $Exports<'prism-react-renderer/es/vendor/prism/includeLangs'>;
}
declare module 'prism-react-renderer/es/vendor/prism/index.js' {
  declare module.exports: $Exports<'prism-react-renderer/es/vendor/prism/index'>;
}
declare module 'prism-react-renderer/es/vendor/prism/prism-core.js' {
  declare module.exports: $Exports<'prism-react-renderer/es/vendor/prism/prism-core'>;
}
declare module 'prism-react-renderer/lib/components/Highlight.js' {
  declare module.exports: $Exports<'prism-react-renderer/lib/components/Highlight'>;
}
declare module 'prism-react-renderer/lib/defaultProps.js' {
  declare module.exports: $Exports<'prism-react-renderer/lib/defaultProps'>;
}
declare module 'prism-react-renderer/lib/index.js' {
  declare module.exports: $Exports<'prism-react-renderer/lib/index'>;
}
declare module 'prism-react-renderer/lib/types.js' {
  declare module.exports: $Exports<'prism-react-renderer/lib/types'>;
}
declare module 'prism-react-renderer/lib/utils/normalizeTokens.js' {
  declare module.exports: $Exports<'prism-react-renderer/lib/utils/normalizeTokens'>;
}
declare module 'prism-react-renderer/lib/utils/themeToDict.js' {
  declare module.exports: $Exports<'prism-react-renderer/lib/utils/themeToDict'>;
}
declare module 'prism-react-renderer/lib/vendor/prism/includeLangs.js' {
  declare module.exports: $Exports<'prism-react-renderer/lib/vendor/prism/includeLangs'>;
}
declare module 'prism-react-renderer/lib/vendor/prism/index.js' {
  declare module.exports: $Exports<'prism-react-renderer/lib/vendor/prism/index'>;
}
declare module 'prism-react-renderer/lib/vendor/prism/prism-core.js' {
  declare module.exports: $Exports<'prism-react-renderer/lib/vendor/prism/prism-core'>;
}
declare module 'prism-react-renderer/themes/dracula.js' {
  declare module.exports: $Exports<'prism-react-renderer/themes/dracula'>;
}
declare module 'prism-react-renderer/themes/duotoneDark.js' {
  declare module.exports: $Exports<'prism-react-renderer/themes/duotoneDark'>;
}
declare module 'prism-react-renderer/themes/duotoneLight.js' {
  declare module.exports: $Exports<'prism-react-renderer/themes/duotoneLight'>;
}
declare module 'prism-react-renderer/themes/nightOwl.js' {
  declare module.exports: $Exports<'prism-react-renderer/themes/nightOwl'>;
}
declare module 'prism-react-renderer/themes/oceanicNext.js' {
  declare module.exports: $Exports<'prism-react-renderer/themes/oceanicNext'>;
}
declare module 'prism-react-renderer/themes/ultramin.js' {
  declare module.exports: $Exports<'prism-react-renderer/themes/ultramin'>;
}
