// flow-typed signature: 914da65c76e12730f3b4e60d17889885
// flow-typed version: <<STUB>>/react-virtualized-auto-sizer_v1.0.2/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-virtualized-auto-sizer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-virtualized-auto-sizer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-virtualized-auto-sizer/dist/index.cjs' {
  declare module.exports: any;
}

declare module 'react-virtualized-auto-sizer/dist/index.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-virtualized-auto-sizer/dist/index.cjs.js' {
  declare module.exports: $Exports<'react-virtualized-auto-sizer/dist/index.cjs'>;
}
declare module 'react-virtualized-auto-sizer/dist/index.esm.js' {
  declare module.exports: $Exports<'react-virtualized-auto-sizer/dist/index.esm'>;
}
