// flow-typed signature: 8416c078446255c2792e5980fa4c381c
// flow-typed version: <<STUB>>/react-debounce-render_v4.0.3/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-debounce-render'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-debounce-render' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-debounce-render/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-debounce-render/lib/index.js' {
  declare module.exports: $Exports<'react-debounce-render/lib/index'>;
}
