// flow-typed signature: ac14c5c7c3e8767ae819a78c6cd4f19d
// flow-typed version: <<STUB>>/redux-persist_v5.10.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-persist'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-persist' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-persist/dist/redux-persist' {
  declare module.exports: any;
}

declare module 'redux-persist/dist/redux-persist.min' {
  declare module.exports: any;
}

declare module 'redux-persist/es/constants' {
  declare module.exports: any;
}

declare module 'redux-persist/es/createMigrate' {
  declare module.exports: any;
}

declare module 'redux-persist/es/createPersistoid' {
  declare module.exports: any;
}

declare module 'redux-persist/es/createTransform' {
  declare module.exports: any;
}

declare module 'redux-persist/es/getStoredState' {
  declare module.exports: any;
}

declare module 'redux-persist/es/index' {
  declare module.exports: any;
}

declare module 'redux-persist/es/integration/getStoredStateMigrateV4' {
  declare module.exports: any;
}

declare module 'redux-persist/es/integration/react' {
  declare module.exports: any;
}

declare module 'redux-persist/es/persistCombineReducers' {
  declare module.exports: any;
}

declare module 'redux-persist/es/persistReducer' {
  declare module.exports: any;
}

declare module 'redux-persist/es/persistStore' {
  declare module.exports: any;
}

declare module 'redux-persist/es/purgeStoredState' {
  declare module.exports: any;
}

declare module 'redux-persist/es/stateReconciler/autoMergeLevel1' {
  declare module.exports: any;
}

declare module 'redux-persist/es/stateReconciler/autoMergeLevel2' {
  declare module.exports: any;
}

declare module 'redux-persist/es/stateReconciler/hardSet' {
  declare module.exports: any;
}

declare module 'redux-persist/es/storage/createWebStorage' {
  declare module.exports: any;
}

declare module 'redux-persist/es/storage/getStorage' {
  declare module.exports: any;
}

declare module 'redux-persist/es/storage/index' {
  declare module.exports: any;
}

declare module 'redux-persist/es/storage/index.native' {
  declare module.exports: any;
}

declare module 'redux-persist/es/storage/session' {
  declare module.exports: any;
}

declare module 'redux-persist/es/types' {
  declare module.exports: any;
}

declare module 'redux-persist/lib/constants' {
  declare module.exports: any;
}

declare module 'redux-persist/lib/createMigrate' {
  declare module.exports: any;
}

declare module 'redux-persist/lib/createPersistoid' {
  declare module.exports: any;
}

declare module 'redux-persist/lib/createTransform' {
  declare module.exports: any;
}

declare module 'redux-persist/lib/getStoredState' {
  declare module.exports: any;
}

declare module 'redux-persist/lib/index' {
  declare module.exports: any;
}

declare module 'redux-persist/lib/integration/getStoredStateMigrateV4' {
  declare module.exports: any;
}

declare module 'redux-persist/lib/integration/react' {
  declare module.exports: any;
}

declare module 'redux-persist/lib/persistCombineReducers' {
  declare module.exports: any;
}

declare module 'redux-persist/lib/persistReducer' {
  declare module.exports: any;
}

declare module 'redux-persist/lib/persistStore' {
  declare module.exports: any;
}

declare module 'redux-persist/lib/purgeStoredState' {
  declare module.exports: any;
}

declare module 'redux-persist/lib/stateReconciler/autoMergeLevel1' {
  declare module.exports: any;
}

declare module 'redux-persist/lib/stateReconciler/autoMergeLevel2' {
  declare module.exports: any;
}

declare module 'redux-persist/lib/stateReconciler/hardSet' {
  declare module.exports: any;
}

declare module 'redux-persist/lib/storage/createWebStorage' {
  declare module.exports: any;
}

declare module 'redux-persist/lib/storage/getStorage' {
  declare module.exports: any;
}

declare module 'redux-persist/lib/storage/index' {
  declare module.exports: any;
}

declare module 'redux-persist/lib/storage/index.native' {
  declare module.exports: any;
}

declare module 'redux-persist/lib/storage/session' {
  declare module.exports: any;
}

declare module 'redux-persist/lib/types' {
  declare module.exports: any;
}

declare module 'redux-persist/src/constants' {
  declare module.exports: any;
}

declare module 'redux-persist/src/createMigrate' {
  declare module.exports: any;
}

declare module 'redux-persist/src/createPersistoid' {
  declare module.exports: any;
}

declare module 'redux-persist/src/createTransform' {
  declare module.exports: any;
}

declare module 'redux-persist/src/getStoredState' {
  declare module.exports: any;
}

declare module 'redux-persist/src/index' {
  declare module.exports: any;
}

declare module 'redux-persist/src/integration/getStoredStateMigrateV4' {
  declare module.exports: any;
}

declare module 'redux-persist/src/integration/react' {
  declare module.exports: any;
}

declare module 'redux-persist/src/persistCombineReducers' {
  declare module.exports: any;
}

declare module 'redux-persist/src/persistReducer' {
  declare module.exports: any;
}

declare module 'redux-persist/src/persistStore' {
  declare module.exports: any;
}

declare module 'redux-persist/src/purgeStoredState' {
  declare module.exports: any;
}

declare module 'redux-persist/src/stateReconciler/autoMergeLevel1' {
  declare module.exports: any;
}

declare module 'redux-persist/src/stateReconciler/autoMergeLevel2' {
  declare module.exports: any;
}

declare module 'redux-persist/src/stateReconciler/hardSet' {
  declare module.exports: any;
}

declare module 'redux-persist/src/storage/createWebStorage' {
  declare module.exports: any;
}

declare module 'redux-persist/src/storage/getStorage' {
  declare module.exports: any;
}

declare module 'redux-persist/src/storage/index' {
  declare module.exports: any;
}

declare module 'redux-persist/src/storage/index.native' {
  declare module.exports: any;
}

declare module 'redux-persist/src/storage/session' {
  declare module.exports: any;
}

declare module 'redux-persist/src/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-persist/dist/redux-persist.js' {
  declare module.exports: $Exports<'redux-persist/dist/redux-persist'>;
}
declare module 'redux-persist/dist/redux-persist.min.js' {
  declare module.exports: $Exports<'redux-persist/dist/redux-persist.min'>;
}
declare module 'redux-persist/es/constants.js' {
  declare module.exports: $Exports<'redux-persist/es/constants'>;
}
declare module 'redux-persist/es/createMigrate.js' {
  declare module.exports: $Exports<'redux-persist/es/createMigrate'>;
}
declare module 'redux-persist/es/createPersistoid.js' {
  declare module.exports: $Exports<'redux-persist/es/createPersistoid'>;
}
declare module 'redux-persist/es/createTransform.js' {
  declare module.exports: $Exports<'redux-persist/es/createTransform'>;
}
declare module 'redux-persist/es/getStoredState.js' {
  declare module.exports: $Exports<'redux-persist/es/getStoredState'>;
}
declare module 'redux-persist/es/index.js' {
  declare module.exports: $Exports<'redux-persist/es/index'>;
}
declare module 'redux-persist/es/integration/getStoredStateMigrateV4.js' {
  declare module.exports: $Exports<'redux-persist/es/integration/getStoredStateMigrateV4'>;
}
declare module 'redux-persist/es/integration/react.js' {
  declare module.exports: $Exports<'redux-persist/es/integration/react'>;
}
declare module 'redux-persist/es/persistCombineReducers.js' {
  declare module.exports: $Exports<'redux-persist/es/persistCombineReducers'>;
}
declare module 'redux-persist/es/persistReducer.js' {
  declare module.exports: $Exports<'redux-persist/es/persistReducer'>;
}
declare module 'redux-persist/es/persistStore.js' {
  declare module.exports: $Exports<'redux-persist/es/persistStore'>;
}
declare module 'redux-persist/es/purgeStoredState.js' {
  declare module.exports: $Exports<'redux-persist/es/purgeStoredState'>;
}
declare module 'redux-persist/es/stateReconciler/autoMergeLevel1.js' {
  declare module.exports: $Exports<'redux-persist/es/stateReconciler/autoMergeLevel1'>;
}
declare module 'redux-persist/es/stateReconciler/autoMergeLevel2.js' {
  declare module.exports: $Exports<'redux-persist/es/stateReconciler/autoMergeLevel2'>;
}
declare module 'redux-persist/es/stateReconciler/hardSet.js' {
  declare module.exports: $Exports<'redux-persist/es/stateReconciler/hardSet'>;
}
declare module 'redux-persist/es/storage/createWebStorage.js' {
  declare module.exports: $Exports<'redux-persist/es/storage/createWebStorage'>;
}
declare module 'redux-persist/es/storage/getStorage.js' {
  declare module.exports: $Exports<'redux-persist/es/storage/getStorage'>;
}
declare module 'redux-persist/es/storage/index.js' {
  declare module.exports: $Exports<'redux-persist/es/storage/index'>;
}
declare module 'redux-persist/es/storage/index.native.js' {
  declare module.exports: $Exports<'redux-persist/es/storage/index.native'>;
}
declare module 'redux-persist/es/storage/session.js' {
  declare module.exports: $Exports<'redux-persist/es/storage/session'>;
}
declare module 'redux-persist/es/types.js' {
  declare module.exports: $Exports<'redux-persist/es/types'>;
}
declare module 'redux-persist/lib/constants.js' {
  declare module.exports: $Exports<'redux-persist/lib/constants'>;
}
declare module 'redux-persist/lib/createMigrate.js' {
  declare module.exports: $Exports<'redux-persist/lib/createMigrate'>;
}
declare module 'redux-persist/lib/createPersistoid.js' {
  declare module.exports: $Exports<'redux-persist/lib/createPersistoid'>;
}
declare module 'redux-persist/lib/createTransform.js' {
  declare module.exports: $Exports<'redux-persist/lib/createTransform'>;
}
declare module 'redux-persist/lib/getStoredState.js' {
  declare module.exports: $Exports<'redux-persist/lib/getStoredState'>;
}
declare module 'redux-persist/lib/index.js' {
  declare module.exports: $Exports<'redux-persist/lib/index'>;
}
declare module 'redux-persist/lib/integration/getStoredStateMigrateV4.js' {
  declare module.exports: $Exports<'redux-persist/lib/integration/getStoredStateMigrateV4'>;
}
declare module 'redux-persist/lib/integration/react.js' {
  declare module.exports: $Exports<'redux-persist/lib/integration/react'>;
}
declare module 'redux-persist/lib/persistCombineReducers.js' {
  declare module.exports: $Exports<'redux-persist/lib/persistCombineReducers'>;
}
declare module 'redux-persist/lib/persistReducer.js' {
  declare module.exports: $Exports<'redux-persist/lib/persistReducer'>;
}
declare module 'redux-persist/lib/persistStore.js' {
  declare module.exports: $Exports<'redux-persist/lib/persistStore'>;
}
declare module 'redux-persist/lib/purgeStoredState.js' {
  declare module.exports: $Exports<'redux-persist/lib/purgeStoredState'>;
}
declare module 'redux-persist/lib/stateReconciler/autoMergeLevel1.js' {
  declare module.exports: $Exports<'redux-persist/lib/stateReconciler/autoMergeLevel1'>;
}
declare module 'redux-persist/lib/stateReconciler/autoMergeLevel2.js' {
  declare module.exports: $Exports<'redux-persist/lib/stateReconciler/autoMergeLevel2'>;
}
declare module 'redux-persist/lib/stateReconciler/hardSet.js' {
  declare module.exports: $Exports<'redux-persist/lib/stateReconciler/hardSet'>;
}
declare module 'redux-persist/lib/storage/createWebStorage.js' {
  declare module.exports: $Exports<'redux-persist/lib/storage/createWebStorage'>;
}
declare module 'redux-persist/lib/storage/getStorage.js' {
  declare module.exports: $Exports<'redux-persist/lib/storage/getStorage'>;
}
declare module 'redux-persist/lib/storage/index.js' {
  declare module.exports: $Exports<'redux-persist/lib/storage/index'>;
}
declare module 'redux-persist/lib/storage/index.native.js' {
  declare module.exports: $Exports<'redux-persist/lib/storage/index.native'>;
}
declare module 'redux-persist/lib/storage/session.js' {
  declare module.exports: $Exports<'redux-persist/lib/storage/session'>;
}
declare module 'redux-persist/lib/types.js' {
  declare module.exports: $Exports<'redux-persist/lib/types'>;
}
declare module 'redux-persist/src/constants.js' {
  declare module.exports: $Exports<'redux-persist/src/constants'>;
}
declare module 'redux-persist/src/createMigrate.js' {
  declare module.exports: $Exports<'redux-persist/src/createMigrate'>;
}
declare module 'redux-persist/src/createPersistoid.js' {
  declare module.exports: $Exports<'redux-persist/src/createPersistoid'>;
}
declare module 'redux-persist/src/createTransform.js' {
  declare module.exports: $Exports<'redux-persist/src/createTransform'>;
}
declare module 'redux-persist/src/getStoredState.js' {
  declare module.exports: $Exports<'redux-persist/src/getStoredState'>;
}
declare module 'redux-persist/src/index.js' {
  declare module.exports: $Exports<'redux-persist/src/index'>;
}
declare module 'redux-persist/src/integration/getStoredStateMigrateV4.js' {
  declare module.exports: $Exports<'redux-persist/src/integration/getStoredStateMigrateV4'>;
}
declare module 'redux-persist/src/integration/react.js' {
  declare module.exports: $Exports<'redux-persist/src/integration/react'>;
}
declare module 'redux-persist/src/persistCombineReducers.js' {
  declare module.exports: $Exports<'redux-persist/src/persistCombineReducers'>;
}
declare module 'redux-persist/src/persistReducer.js' {
  declare module.exports: $Exports<'redux-persist/src/persistReducer'>;
}
declare module 'redux-persist/src/persistStore.js' {
  declare module.exports: $Exports<'redux-persist/src/persistStore'>;
}
declare module 'redux-persist/src/purgeStoredState.js' {
  declare module.exports: $Exports<'redux-persist/src/purgeStoredState'>;
}
declare module 'redux-persist/src/stateReconciler/autoMergeLevel1.js' {
  declare module.exports: $Exports<'redux-persist/src/stateReconciler/autoMergeLevel1'>;
}
declare module 'redux-persist/src/stateReconciler/autoMergeLevel2.js' {
  declare module.exports: $Exports<'redux-persist/src/stateReconciler/autoMergeLevel2'>;
}
declare module 'redux-persist/src/stateReconciler/hardSet.js' {
  declare module.exports: $Exports<'redux-persist/src/stateReconciler/hardSet'>;
}
declare module 'redux-persist/src/storage/createWebStorage.js' {
  declare module.exports: $Exports<'redux-persist/src/storage/createWebStorage'>;
}
declare module 'redux-persist/src/storage/getStorage.js' {
  declare module.exports: $Exports<'redux-persist/src/storage/getStorage'>;
}
declare module 'redux-persist/src/storage/index.js' {
  declare module.exports: $Exports<'redux-persist/src/storage/index'>;
}
declare module 'redux-persist/src/storage/index.native.js' {
  declare module.exports: $Exports<'redux-persist/src/storage/index.native'>;
}
declare module 'redux-persist/src/storage/session.js' {
  declare module.exports: $Exports<'redux-persist/src/storage/session'>;
}
declare module 'redux-persist/src/types.js' {
  declare module.exports: $Exports<'redux-persist/src/types'>;
}
