// flow-typed signature: 068e45937700fb48646a6b80285d5804
// flow-typed version: <<STUB>>/remote-redux-devtools_v0.5.16/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remote-redux-devtools'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remote-redux-devtools' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'remote-redux-devtools/lib/configureStore' {
  declare module.exports: any;
}

declare module 'remote-redux-devtools/lib/constants' {
  declare module.exports: any;
}

declare module 'remote-redux-devtools/lib/devTools' {
  declare module.exports: any;
}

declare module 'remote-redux-devtools/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'remote-redux-devtools/lib/configureStore.js' {
  declare module.exports: $Exports<'remote-redux-devtools/lib/configureStore'>;
}
declare module 'remote-redux-devtools/lib/constants.js' {
  declare module.exports: $Exports<'remote-redux-devtools/lib/constants'>;
}
declare module 'remote-redux-devtools/lib/devTools.js' {
  declare module.exports: $Exports<'remote-redux-devtools/lib/devTools'>;
}
declare module 'remote-redux-devtools/lib/index.js' {
  declare module.exports: $Exports<'remote-redux-devtools/lib/index'>;
}
