// flow-typed signature: 06cae6786a7bab166b894590a59b8780
// flow-typed version: <<STUB>>/rsocket-flowable_v0.0.6/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rsocket-flowable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rsocket-flowable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rsocket-flowable/build/Flowable' {
  declare module.exports: any;
}

declare module 'rsocket-flowable/build/FlowableMapOperator' {
  declare module.exports: any;
}

declare module 'rsocket-flowable/build/FlowableRequestOperator' {
  declare module.exports: any;
}

declare module 'rsocket-flowable/build/FlowableTakeOperator' {
  declare module.exports: any;
}

declare module 'rsocket-flowable/build/FlowableTimer' {
  declare module.exports: any;
}

declare module 'rsocket-flowable/build/haste/rsocket-flowable' {
  declare module.exports: any;
}

declare module 'rsocket-flowable/build/index' {
  declare module.exports: any;
}

declare module 'rsocket-flowable/build/Single' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rsocket-flowable/build/Flowable.js' {
  declare module.exports: $Exports<'rsocket-flowable/build/Flowable'>;
}
declare module 'rsocket-flowable/build/FlowableMapOperator.js' {
  declare module.exports: $Exports<'rsocket-flowable/build/FlowableMapOperator'>;
}
declare module 'rsocket-flowable/build/FlowableRequestOperator.js' {
  declare module.exports: $Exports<'rsocket-flowable/build/FlowableRequestOperator'>;
}
declare module 'rsocket-flowable/build/FlowableTakeOperator.js' {
  declare module.exports: $Exports<'rsocket-flowable/build/FlowableTakeOperator'>;
}
declare module 'rsocket-flowable/build/FlowableTimer.js' {
  declare module.exports: $Exports<'rsocket-flowable/build/FlowableTimer'>;
}
declare module 'rsocket-flowable/build/haste/rsocket-flowable.js' {
  declare module.exports: $Exports<'rsocket-flowable/build/haste/rsocket-flowable'>;
}
declare module 'rsocket-flowable/build/index.js' {
  declare module.exports: $Exports<'rsocket-flowable/build/index'>;
}
declare module 'rsocket-flowable/build/Single.js' {
  declare module.exports: $Exports<'rsocket-flowable/build/Single'>;
}
