// flow-typed signature: ab12cb0bb6ca55414cab3e4d58ebf17e
// flow-typed version: <<STUB>>/vis_v4.21.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vis'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vis' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vis/dist/vis-graph3d.min' {
  declare module.exports: any;
}

declare module 'vis/dist/vis-network.min' {
  declare module.exports: any;
}

declare module 'vis/dist/vis-timeline-graph2d.min' {
  declare module.exports: any;
}

declare module 'vis/dist/vis' {
  declare module.exports: any;
}

declare module 'vis/dist/vis.min' {
  declare module.exports: any;
}

declare module 'vis/docs/js/bootstrap' {
  declare module.exports: any;
}

declare module 'vis/docs/js/bootstrap.min' {
  declare module.exports: any;
}

declare module 'vis/docs/js/docs.min' {
  declare module.exports: any;
}

declare module 'vis/docs/js/googleAnalytics' {
  declare module.exports: any;
}

declare module 'vis/docs/js/ie-emulation-modes-warning' {
  declare module.exports: any;
}

declare module 'vis/docs/js/ie10-viewport-bug-workaround' {
  declare module.exports: any;
}

declare module 'vis/docs/js/jquery.highlight' {
  declare module.exports: any;
}

declare module 'vis/docs/js/jquery.min' {
  declare module.exports: any;
}

declare module 'vis/docs/js/jquery.url.min' {
  declare module.exports: any;
}

declare module 'vis/docs/js/main' {
  declare module.exports: any;
}

declare module 'vis/docs/js/prettify/lang-apollo' {
  declare module.exports: any;
}

declare module 'vis/docs/js/prettify/lang-css' {
  declare module.exports: any;
}

declare module 'vis/docs/js/prettify/lang-hs' {
  declare module.exports: any;
}

declare module 'vis/docs/js/prettify/lang-lisp' {
  declare module.exports: any;
}

declare module 'vis/docs/js/prettify/lang-lua' {
  declare module.exports: any;
}

declare module 'vis/docs/js/prettify/lang-ml' {
  declare module.exports: any;
}

declare module 'vis/docs/js/prettify/lang-proto' {
  declare module.exports: any;
}

declare module 'vis/docs/js/prettify/lang-scala' {
  declare module.exports: any;
}

declare module 'vis/docs/js/prettify/lang-sql' {
  declare module.exports: any;
}

declare module 'vis/docs/js/prettify/lang-vb' {
  declare module.exports: any;
}

declare module 'vis/docs/js/prettify/lang-vhdl' {
  declare module.exports: any;
}

declare module 'vis/docs/js/prettify/lang-wiki' {
  declare module.exports: any;
}

declare module 'vis/docs/js/prettify/lang-yaml' {
  declare module.exports: any;
}

declare module 'vis/docs/js/prettify/prettify' {
  declare module.exports: any;
}

declare module 'vis/docs/js/smooth-scroll.min' {
  declare module.exports: any;
}

declare module 'vis/docs/js/tipuesearch.config' {
  declare module.exports: any;
}

declare module 'vis/docs/js/tipuesearch' {
  declare module.exports: any;
}

declare module 'vis/docs/js/tipuesearch.min' {
  declare module.exports: any;
}

declare module 'vis/docs/js/toggleTable' {
  declare module.exports: any;
}

declare module 'vis/examples/graph3d/playground/csv2array' {
  declare module.exports: any;
}

declare module 'vis/examples/graph3d/playground/playground' {
  declare module.exports: any;
}

declare module 'vis/examples/graph3d/playground/prettify/lang-apollo' {
  declare module.exports: any;
}

declare module 'vis/examples/graph3d/playground/prettify/lang-css' {
  declare module.exports: any;
}

declare module 'vis/examples/graph3d/playground/prettify/lang-hs' {
  declare module.exports: any;
}

declare module 'vis/examples/graph3d/playground/prettify/lang-lisp' {
  declare module.exports: any;
}

declare module 'vis/examples/graph3d/playground/prettify/lang-lua' {
  declare module.exports: any;
}

declare module 'vis/examples/graph3d/playground/prettify/lang-ml' {
  declare module.exports: any;
}

declare module 'vis/examples/graph3d/playground/prettify/lang-proto' {
  declare module.exports: any;
}

declare module 'vis/examples/graph3d/playground/prettify/lang-scala' {
  declare module.exports: any;
}

declare module 'vis/examples/graph3d/playground/prettify/lang-sql' {
  declare module.exports: any;
}

declare module 'vis/examples/graph3d/playground/prettify/lang-vb' {
  declare module.exports: any;
}

declare module 'vis/examples/graph3d/playground/prettify/lang-vhdl' {
  declare module.exports: any;
}

declare module 'vis/examples/graph3d/playground/prettify/lang-wiki' {
  declare module.exports: any;
}

declare module 'vis/examples/graph3d/playground/prettify/lang-yaml' {
  declare module.exports: any;
}

declare module 'vis/examples/graph3d/playground/prettify/prettify' {
  declare module.exports: any;
}

declare module 'vis/examples/network/datasources/largeHierarchicalDataset' {
  declare module.exports: any;
}

declare module 'vis/examples/network/datasources/WorldCup2014' {
  declare module.exports: any;
}

declare module 'vis/examples/network/exampleApplications/disassemblerExample' {
  declare module.exports: any;
}

declare module 'vis/examples/network/exampleUtil' {
  declare module.exports: any;
}

declare module 'vis/examples/timeline/other/requirejs/scripts/main' {
  declare module.exports: any;
}

declare module 'vis/examples/timeline/other/requirejs/scripts/require' {
  declare module.exports: any;
}

declare module 'vis/gulpfile' {
  declare module.exports: any;
}

declare module 'vis/index-graph3d' {
  declare module.exports: any;
}

declare module 'vis/index-network' {
  declare module.exports: any;
}

declare module 'vis/index-timeline-graph2d' {
  declare module.exports: any;
}

declare module 'vis/lib/DataSet' {
  declare module.exports: any;
}

declare module 'vis/lib/DataView' {
  declare module.exports: any;
}

declare module 'vis/lib/DOMutil' {
  declare module.exports: any;
}

declare module 'vis/lib/graph3d/Camera' {
  declare module.exports: any;
}

declare module 'vis/lib/graph3d/DataGroup' {
  declare module.exports: any;
}

declare module 'vis/lib/graph3d/Filter' {
  declare module.exports: any;
}

declare module 'vis/lib/graph3d/Graph3d' {
  declare module.exports: any;
}

declare module 'vis/lib/graph3d/options' {
  declare module.exports: any;
}

declare module 'vis/lib/graph3d/Point2d' {
  declare module.exports: any;
}

declare module 'vis/lib/graph3d/Point3d' {
  declare module.exports: any;
}

declare module 'vis/lib/graph3d/Range' {
  declare module.exports: any;
}

declare module 'vis/lib/graph3d/Settings' {
  declare module.exports: any;
}

declare module 'vis/lib/graph3d/Slider' {
  declare module.exports: any;
}

declare module 'vis/lib/graph3d/StepNumber' {
  declare module.exports: any;
}

declare module 'vis/lib/hammerUtil' {
  declare module.exports: any;
}

declare module 'vis/lib/header' {
  declare module.exports: any;
}

declare module 'vis/lib/module/hammer' {
  declare module.exports: any;
}

declare module 'vis/lib/module/moment' {
  declare module.exports: any;
}

declare module 'vis/lib/module/uuid' {
  declare module.exports: any;
}

declare module 'vis/lib/network/CachedImage' {
  declare module.exports: any;
}

declare module 'vis/lib/network/dotparser' {
  declare module.exports: any;
}

declare module 'vis/lib/network/gephiParser' {
  declare module.exports: any;
}

declare module 'vis/lib/network/Images' {
  declare module.exports: any;
}

declare module 'vis/lib/network/locales' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/Canvas' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/CanvasRenderer' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/Clustering' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/components/algorithms/FloydWarshall' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/components/DirectionStrategy' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/components/Edge' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/components/edges/BezierEdgeDynamic' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/components/edges/BezierEdgeStatic' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/components/edges/CubicBezierEdge' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/components/edges/StraightEdge' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/components/edges/util/BezierEdgeBase' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/components/edges/util/CubicBezierEdgeBase' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/components/edges/util/EdgeBase' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/components/edges/util/EndPoints' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/components/NavigationHandler' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/components/Node' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/components/nodes/Cluster' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/components/nodes/shapes/Box' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/components/nodes/shapes/Circle' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/components/nodes/shapes/CircularImage' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/components/nodes/shapes/Database' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/components/nodes/shapes/Diamond' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/components/nodes/shapes/Dot' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/components/nodes/shapes/Ellipse' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/components/nodes/shapes/Hexagon' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/components/nodes/shapes/Icon' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/components/nodes/shapes/Image' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/components/nodes/shapes/Square' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/components/nodes/shapes/Star' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/components/nodes/shapes/Text' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/components/nodes/shapes/Triangle' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/components/nodes/shapes/TriangleDown' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/components/nodes/util/CircleImageBase' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/components/nodes/util/NodeBase' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/components/nodes/util/ShapeBase' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/components/physics/BarnesHutSolver' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/components/physics/CentralGravitySolver' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/components/physics/FA2BasedCentralGravitySolver' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/components/physics/FA2BasedRepulsionSolver' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/components/physics/HierarchicalRepulsionSolver' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/components/physics/HierarchicalSpringSolver' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/components/physics/RepulsionSolver' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/components/physics/SpringSolver' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/components/shared/ComponentUtil' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/components/shared/Label' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/components/shared/LabelAccumulator' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/components/shared/LabelSplitter' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/EdgesHandler' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/Groups' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/InteractionHandler' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/KamadaKawai' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/LayoutEngine' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/ManipulationSystem' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/NodesHandler' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/PhysicsEngine' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/SelectionHandler' {
  declare module.exports: any;
}

declare module 'vis/lib/network/modules/View' {
  declare module.exports: any;
}

declare module 'vis/lib/network/Network' {
  declare module.exports: any;
}

declare module 'vis/lib/network/NetworkUtil' {
  declare module.exports: any;
}

declare module 'vis/lib/network/options' {
  declare module.exports: any;
}

declare module 'vis/lib/network/shapes' {
  declare module.exports: any;
}

declare module 'vis/lib/Queue' {
  declare module.exports: any;
}

declare module 'vis/lib/shared/Activator' {
  declare module.exports: any;
}

declare module 'vis/lib/shared/ColorPicker' {
  declare module.exports: any;
}

declare module 'vis/lib/shared/Configurator' {
  declare module.exports: any;
}

declare module 'vis/lib/shared/Popup' {
  declare module.exports: any;
}

declare module 'vis/lib/shared/Validator' {
  declare module.exports: any;
}

declare module 'vis/lib/timeline/component/BackgroundGroup' {
  declare module.exports: any;
}

declare module 'vis/lib/timeline/component/Component' {
  declare module.exports: any;
}

declare module 'vis/lib/timeline/component/CurrentTime' {
  declare module.exports: any;
}

declare module 'vis/lib/timeline/component/CustomTime' {
  declare module.exports: any;
}

declare module 'vis/lib/timeline/component/DataAxis' {
  declare module.exports: any;
}

declare module 'vis/lib/timeline/component/DataScale' {
  declare module.exports: any;
}

declare module 'vis/lib/timeline/component/graph2d_types/bar' {
  declare module.exports: any;
}

declare module 'vis/lib/timeline/component/graph2d_types/line' {
  declare module.exports: any;
}

declare module 'vis/lib/timeline/component/graph2d_types/points' {
  declare module.exports: any;
}

declare module 'vis/lib/timeline/component/GraphGroup' {
  declare module.exports: any;
}

declare module 'vis/lib/timeline/component/Group' {
  declare module.exports: any;
}

declare module 'vis/lib/timeline/component/item/BackgroundItem' {
  declare module.exports: any;
}

declare module 'vis/lib/timeline/component/item/BoxItem' {
  declare module.exports: any;
}

declare module 'vis/lib/timeline/component/item/Item' {
  declare module.exports: any;
}

declare module 'vis/lib/timeline/component/item/PointItem' {
  declare module.exports: any;
}

declare module 'vis/lib/timeline/component/item/RangeItem' {
  declare module.exports: any;
}

declare module 'vis/lib/timeline/component/ItemSet' {
  declare module.exports: any;
}

declare module 'vis/lib/timeline/component/Legend' {
  declare module.exports: any;
}

declare module 'vis/lib/timeline/component/LineGraph' {
  declare module.exports: any;
}

declare module 'vis/lib/timeline/component/TimeAxis' {
  declare module.exports: any;
}

declare module 'vis/lib/timeline/Core' {
  declare module.exports: any;
}

declare module 'vis/lib/timeline/DateUtil' {
  declare module.exports: any;
}

declare module 'vis/lib/timeline/Graph2d' {
  declare module.exports: any;
}

declare module 'vis/lib/timeline/locales' {
  declare module.exports: any;
}

declare module 'vis/lib/timeline/optionsGraph2d' {
  declare module.exports: any;
}

declare module 'vis/lib/timeline/optionsTimeline' {
  declare module.exports: any;
}

declare module 'vis/lib/timeline/Range' {
  declare module.exports: any;
}

declare module 'vis/lib/timeline/Stack' {
  declare module.exports: any;
}

declare module 'vis/lib/timeline/Timeline' {
  declare module.exports: any;
}

declare module 'vis/lib/timeline/TimeStep' {
  declare module.exports: any;
}

declare module 'vis/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vis/dist/vis-graph3d.min.js' {
  declare module.exports: $Exports<'vis/dist/vis-graph3d.min'>;
}
declare module 'vis/dist/vis-network.min.js' {
  declare module.exports: $Exports<'vis/dist/vis-network.min'>;
}
declare module 'vis/dist/vis-timeline-graph2d.min.js' {
  declare module.exports: $Exports<'vis/dist/vis-timeline-graph2d.min'>;
}
declare module 'vis/dist/vis.js' {
  declare module.exports: $Exports<'vis/dist/vis'>;
}
declare module 'vis/dist/vis.min.js' {
  declare module.exports: $Exports<'vis/dist/vis.min'>;
}
declare module 'vis/docs/js/bootstrap.js' {
  declare module.exports: $Exports<'vis/docs/js/bootstrap'>;
}
declare module 'vis/docs/js/bootstrap.min.js' {
  declare module.exports: $Exports<'vis/docs/js/bootstrap.min'>;
}
declare module 'vis/docs/js/docs.min.js' {
  declare module.exports: $Exports<'vis/docs/js/docs.min'>;
}
declare module 'vis/docs/js/googleAnalytics.js' {
  declare module.exports: $Exports<'vis/docs/js/googleAnalytics'>;
}
declare module 'vis/docs/js/ie-emulation-modes-warning.js' {
  declare module.exports: $Exports<'vis/docs/js/ie-emulation-modes-warning'>;
}
declare module 'vis/docs/js/ie10-viewport-bug-workaround.js' {
  declare module.exports: $Exports<'vis/docs/js/ie10-viewport-bug-workaround'>;
}
declare module 'vis/docs/js/jquery.highlight.js' {
  declare module.exports: $Exports<'vis/docs/js/jquery.highlight'>;
}
declare module 'vis/docs/js/jquery.min.js' {
  declare module.exports: $Exports<'vis/docs/js/jquery.min'>;
}
declare module 'vis/docs/js/jquery.url.min.js' {
  declare module.exports: $Exports<'vis/docs/js/jquery.url.min'>;
}
declare module 'vis/docs/js/main.js' {
  declare module.exports: $Exports<'vis/docs/js/main'>;
}
declare module 'vis/docs/js/prettify/lang-apollo.js' {
  declare module.exports: $Exports<'vis/docs/js/prettify/lang-apollo'>;
}
declare module 'vis/docs/js/prettify/lang-css.js' {
  declare module.exports: $Exports<'vis/docs/js/prettify/lang-css'>;
}
declare module 'vis/docs/js/prettify/lang-hs.js' {
  declare module.exports: $Exports<'vis/docs/js/prettify/lang-hs'>;
}
declare module 'vis/docs/js/prettify/lang-lisp.js' {
  declare module.exports: $Exports<'vis/docs/js/prettify/lang-lisp'>;
}
declare module 'vis/docs/js/prettify/lang-lua.js' {
  declare module.exports: $Exports<'vis/docs/js/prettify/lang-lua'>;
}
declare module 'vis/docs/js/prettify/lang-ml.js' {
  declare module.exports: $Exports<'vis/docs/js/prettify/lang-ml'>;
}
declare module 'vis/docs/js/prettify/lang-proto.js' {
  declare module.exports: $Exports<'vis/docs/js/prettify/lang-proto'>;
}
declare module 'vis/docs/js/prettify/lang-scala.js' {
  declare module.exports: $Exports<'vis/docs/js/prettify/lang-scala'>;
}
declare module 'vis/docs/js/prettify/lang-sql.js' {
  declare module.exports: $Exports<'vis/docs/js/prettify/lang-sql'>;
}
declare module 'vis/docs/js/prettify/lang-vb.js' {
  declare module.exports: $Exports<'vis/docs/js/prettify/lang-vb'>;
}
declare module 'vis/docs/js/prettify/lang-vhdl.js' {
  declare module.exports: $Exports<'vis/docs/js/prettify/lang-vhdl'>;
}
declare module 'vis/docs/js/prettify/lang-wiki.js' {
  declare module.exports: $Exports<'vis/docs/js/prettify/lang-wiki'>;
}
declare module 'vis/docs/js/prettify/lang-yaml.js' {
  declare module.exports: $Exports<'vis/docs/js/prettify/lang-yaml'>;
}
declare module 'vis/docs/js/prettify/prettify.js' {
  declare module.exports: $Exports<'vis/docs/js/prettify/prettify'>;
}
declare module 'vis/docs/js/smooth-scroll.min.js' {
  declare module.exports: $Exports<'vis/docs/js/smooth-scroll.min'>;
}
declare module 'vis/docs/js/tipuesearch.config.js' {
  declare module.exports: $Exports<'vis/docs/js/tipuesearch.config'>;
}
declare module 'vis/docs/js/tipuesearch.js' {
  declare module.exports: $Exports<'vis/docs/js/tipuesearch'>;
}
declare module 'vis/docs/js/tipuesearch.min.js' {
  declare module.exports: $Exports<'vis/docs/js/tipuesearch.min'>;
}
declare module 'vis/docs/js/toggleTable.js' {
  declare module.exports: $Exports<'vis/docs/js/toggleTable'>;
}
declare module 'vis/examples/graph3d/playground/csv2array.js' {
  declare module.exports: $Exports<'vis/examples/graph3d/playground/csv2array'>;
}
declare module 'vis/examples/graph3d/playground/playground.js' {
  declare module.exports: $Exports<'vis/examples/graph3d/playground/playground'>;
}
declare module 'vis/examples/graph3d/playground/prettify/lang-apollo.js' {
  declare module.exports: $Exports<'vis/examples/graph3d/playground/prettify/lang-apollo'>;
}
declare module 'vis/examples/graph3d/playground/prettify/lang-css.js' {
  declare module.exports: $Exports<'vis/examples/graph3d/playground/prettify/lang-css'>;
}
declare module 'vis/examples/graph3d/playground/prettify/lang-hs.js' {
  declare module.exports: $Exports<'vis/examples/graph3d/playground/prettify/lang-hs'>;
}
declare module 'vis/examples/graph3d/playground/prettify/lang-lisp.js' {
  declare module.exports: $Exports<'vis/examples/graph3d/playground/prettify/lang-lisp'>;
}
declare module 'vis/examples/graph3d/playground/prettify/lang-lua.js' {
  declare module.exports: $Exports<'vis/examples/graph3d/playground/prettify/lang-lua'>;
}
declare module 'vis/examples/graph3d/playground/prettify/lang-ml.js' {
  declare module.exports: $Exports<'vis/examples/graph3d/playground/prettify/lang-ml'>;
}
declare module 'vis/examples/graph3d/playground/prettify/lang-proto.js' {
  declare module.exports: $Exports<'vis/examples/graph3d/playground/prettify/lang-proto'>;
}
declare module 'vis/examples/graph3d/playground/prettify/lang-scala.js' {
  declare module.exports: $Exports<'vis/examples/graph3d/playground/prettify/lang-scala'>;
}
declare module 'vis/examples/graph3d/playground/prettify/lang-sql.js' {
  declare module.exports: $Exports<'vis/examples/graph3d/playground/prettify/lang-sql'>;
}
declare module 'vis/examples/graph3d/playground/prettify/lang-vb.js' {
  declare module.exports: $Exports<'vis/examples/graph3d/playground/prettify/lang-vb'>;
}
declare module 'vis/examples/graph3d/playground/prettify/lang-vhdl.js' {
  declare module.exports: $Exports<'vis/examples/graph3d/playground/prettify/lang-vhdl'>;
}
declare module 'vis/examples/graph3d/playground/prettify/lang-wiki.js' {
  declare module.exports: $Exports<'vis/examples/graph3d/playground/prettify/lang-wiki'>;
}
declare module 'vis/examples/graph3d/playground/prettify/lang-yaml.js' {
  declare module.exports: $Exports<'vis/examples/graph3d/playground/prettify/lang-yaml'>;
}
declare module 'vis/examples/graph3d/playground/prettify/prettify.js' {
  declare module.exports: $Exports<'vis/examples/graph3d/playground/prettify/prettify'>;
}
declare module 'vis/examples/network/datasources/largeHierarchicalDataset.js' {
  declare module.exports: $Exports<'vis/examples/network/datasources/largeHierarchicalDataset'>;
}
declare module 'vis/examples/network/datasources/WorldCup2014.js' {
  declare module.exports: $Exports<'vis/examples/network/datasources/WorldCup2014'>;
}
declare module 'vis/examples/network/exampleApplications/disassemblerExample.js' {
  declare module.exports: $Exports<'vis/examples/network/exampleApplications/disassemblerExample'>;
}
declare module 'vis/examples/network/exampleUtil.js' {
  declare module.exports: $Exports<'vis/examples/network/exampleUtil'>;
}
declare module 'vis/examples/timeline/other/requirejs/scripts/main.js' {
  declare module.exports: $Exports<'vis/examples/timeline/other/requirejs/scripts/main'>;
}
declare module 'vis/examples/timeline/other/requirejs/scripts/require.js' {
  declare module.exports: $Exports<'vis/examples/timeline/other/requirejs/scripts/require'>;
}
declare module 'vis/gulpfile.js' {
  declare module.exports: $Exports<'vis/gulpfile'>;
}
declare module 'vis/index-graph3d.js' {
  declare module.exports: $Exports<'vis/index-graph3d'>;
}
declare module 'vis/index-network.js' {
  declare module.exports: $Exports<'vis/index-network'>;
}
declare module 'vis/index-timeline-graph2d.js' {
  declare module.exports: $Exports<'vis/index-timeline-graph2d'>;
}
declare module 'vis/index' {
  declare module.exports: $Exports<'vis'>;
}
declare module 'vis/index.js' {
  declare module.exports: $Exports<'vis'>;
}
declare module 'vis/lib/DataSet.js' {
  declare module.exports: $Exports<'vis/lib/DataSet'>;
}
declare module 'vis/lib/DataView.js' {
  declare module.exports: $Exports<'vis/lib/DataView'>;
}
declare module 'vis/lib/DOMutil.js' {
  declare module.exports: $Exports<'vis/lib/DOMutil'>;
}
declare module 'vis/lib/graph3d/Camera.js' {
  declare module.exports: $Exports<'vis/lib/graph3d/Camera'>;
}
declare module 'vis/lib/graph3d/DataGroup.js' {
  declare module.exports: $Exports<'vis/lib/graph3d/DataGroup'>;
}
declare module 'vis/lib/graph3d/Filter.js' {
  declare module.exports: $Exports<'vis/lib/graph3d/Filter'>;
}
declare module 'vis/lib/graph3d/Graph3d.js' {
  declare module.exports: $Exports<'vis/lib/graph3d/Graph3d'>;
}
declare module 'vis/lib/graph3d/options.js' {
  declare module.exports: $Exports<'vis/lib/graph3d/options'>;
}
declare module 'vis/lib/graph3d/Point2d.js' {
  declare module.exports: $Exports<'vis/lib/graph3d/Point2d'>;
}
declare module 'vis/lib/graph3d/Point3d.js' {
  declare module.exports: $Exports<'vis/lib/graph3d/Point3d'>;
}
declare module 'vis/lib/graph3d/Range.js' {
  declare module.exports: $Exports<'vis/lib/graph3d/Range'>;
}
declare module 'vis/lib/graph3d/Settings.js' {
  declare module.exports: $Exports<'vis/lib/graph3d/Settings'>;
}
declare module 'vis/lib/graph3d/Slider.js' {
  declare module.exports: $Exports<'vis/lib/graph3d/Slider'>;
}
declare module 'vis/lib/graph3d/StepNumber.js' {
  declare module.exports: $Exports<'vis/lib/graph3d/StepNumber'>;
}
declare module 'vis/lib/hammerUtil.js' {
  declare module.exports: $Exports<'vis/lib/hammerUtil'>;
}
declare module 'vis/lib/header.js' {
  declare module.exports: $Exports<'vis/lib/header'>;
}
declare module 'vis/lib/module/hammer.js' {
  declare module.exports: $Exports<'vis/lib/module/hammer'>;
}
declare module 'vis/lib/module/moment.js' {
  declare module.exports: $Exports<'vis/lib/module/moment'>;
}
declare module 'vis/lib/module/uuid.js' {
  declare module.exports: $Exports<'vis/lib/module/uuid'>;
}
declare module 'vis/lib/network/CachedImage.js' {
  declare module.exports: $Exports<'vis/lib/network/CachedImage'>;
}
declare module 'vis/lib/network/dotparser.js' {
  declare module.exports: $Exports<'vis/lib/network/dotparser'>;
}
declare module 'vis/lib/network/gephiParser.js' {
  declare module.exports: $Exports<'vis/lib/network/gephiParser'>;
}
declare module 'vis/lib/network/Images.js' {
  declare module.exports: $Exports<'vis/lib/network/Images'>;
}
declare module 'vis/lib/network/locales.js' {
  declare module.exports: $Exports<'vis/lib/network/locales'>;
}
declare module 'vis/lib/network/modules/Canvas.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/Canvas'>;
}
declare module 'vis/lib/network/modules/CanvasRenderer.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/CanvasRenderer'>;
}
declare module 'vis/lib/network/modules/Clustering.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/Clustering'>;
}
declare module 'vis/lib/network/modules/components/algorithms/FloydWarshall.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/components/algorithms/FloydWarshall'>;
}
declare module 'vis/lib/network/modules/components/DirectionStrategy.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/components/DirectionStrategy'>;
}
declare module 'vis/lib/network/modules/components/Edge.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/components/Edge'>;
}
declare module 'vis/lib/network/modules/components/edges/BezierEdgeDynamic.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/components/edges/BezierEdgeDynamic'>;
}
declare module 'vis/lib/network/modules/components/edges/BezierEdgeStatic.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/components/edges/BezierEdgeStatic'>;
}
declare module 'vis/lib/network/modules/components/edges/CubicBezierEdge.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/components/edges/CubicBezierEdge'>;
}
declare module 'vis/lib/network/modules/components/edges/StraightEdge.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/components/edges/StraightEdge'>;
}
declare module 'vis/lib/network/modules/components/edges/util/BezierEdgeBase.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/components/edges/util/BezierEdgeBase'>;
}
declare module 'vis/lib/network/modules/components/edges/util/CubicBezierEdgeBase.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/components/edges/util/CubicBezierEdgeBase'>;
}
declare module 'vis/lib/network/modules/components/edges/util/EdgeBase.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/components/edges/util/EdgeBase'>;
}
declare module 'vis/lib/network/modules/components/edges/util/EndPoints.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/components/edges/util/EndPoints'>;
}
declare module 'vis/lib/network/modules/components/NavigationHandler.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/components/NavigationHandler'>;
}
declare module 'vis/lib/network/modules/components/Node.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/components/Node'>;
}
declare module 'vis/lib/network/modules/components/nodes/Cluster.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/components/nodes/Cluster'>;
}
declare module 'vis/lib/network/modules/components/nodes/shapes/Box.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/components/nodes/shapes/Box'>;
}
declare module 'vis/lib/network/modules/components/nodes/shapes/Circle.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/components/nodes/shapes/Circle'>;
}
declare module 'vis/lib/network/modules/components/nodes/shapes/CircularImage.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/components/nodes/shapes/CircularImage'>;
}
declare module 'vis/lib/network/modules/components/nodes/shapes/Database.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/components/nodes/shapes/Database'>;
}
declare module 'vis/lib/network/modules/components/nodes/shapes/Diamond.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/components/nodes/shapes/Diamond'>;
}
declare module 'vis/lib/network/modules/components/nodes/shapes/Dot.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/components/nodes/shapes/Dot'>;
}
declare module 'vis/lib/network/modules/components/nodes/shapes/Ellipse.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/components/nodes/shapes/Ellipse'>;
}
declare module 'vis/lib/network/modules/components/nodes/shapes/Hexagon.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/components/nodes/shapes/Hexagon'>;
}
declare module 'vis/lib/network/modules/components/nodes/shapes/Icon.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/components/nodes/shapes/Icon'>;
}
declare module 'vis/lib/network/modules/components/nodes/shapes/Image.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/components/nodes/shapes/Image'>;
}
declare module 'vis/lib/network/modules/components/nodes/shapes/Square.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/components/nodes/shapes/Square'>;
}
declare module 'vis/lib/network/modules/components/nodes/shapes/Star.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/components/nodes/shapes/Star'>;
}
declare module 'vis/lib/network/modules/components/nodes/shapes/Text.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/components/nodes/shapes/Text'>;
}
declare module 'vis/lib/network/modules/components/nodes/shapes/Triangle.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/components/nodes/shapes/Triangle'>;
}
declare module 'vis/lib/network/modules/components/nodes/shapes/TriangleDown.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/components/nodes/shapes/TriangleDown'>;
}
declare module 'vis/lib/network/modules/components/nodes/util/CircleImageBase.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/components/nodes/util/CircleImageBase'>;
}
declare module 'vis/lib/network/modules/components/nodes/util/NodeBase.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/components/nodes/util/NodeBase'>;
}
declare module 'vis/lib/network/modules/components/nodes/util/ShapeBase.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/components/nodes/util/ShapeBase'>;
}
declare module 'vis/lib/network/modules/components/physics/BarnesHutSolver.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/components/physics/BarnesHutSolver'>;
}
declare module 'vis/lib/network/modules/components/physics/CentralGravitySolver.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/components/physics/CentralGravitySolver'>;
}
declare module 'vis/lib/network/modules/components/physics/FA2BasedCentralGravitySolver.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/components/physics/FA2BasedCentralGravitySolver'>;
}
declare module 'vis/lib/network/modules/components/physics/FA2BasedRepulsionSolver.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/components/physics/FA2BasedRepulsionSolver'>;
}
declare module 'vis/lib/network/modules/components/physics/HierarchicalRepulsionSolver.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/components/physics/HierarchicalRepulsionSolver'>;
}
declare module 'vis/lib/network/modules/components/physics/HierarchicalSpringSolver.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/components/physics/HierarchicalSpringSolver'>;
}
declare module 'vis/lib/network/modules/components/physics/RepulsionSolver.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/components/physics/RepulsionSolver'>;
}
declare module 'vis/lib/network/modules/components/physics/SpringSolver.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/components/physics/SpringSolver'>;
}
declare module 'vis/lib/network/modules/components/shared/ComponentUtil.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/components/shared/ComponentUtil'>;
}
declare module 'vis/lib/network/modules/components/shared/Label.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/components/shared/Label'>;
}
declare module 'vis/lib/network/modules/components/shared/LabelAccumulator.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/components/shared/LabelAccumulator'>;
}
declare module 'vis/lib/network/modules/components/shared/LabelSplitter.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/components/shared/LabelSplitter'>;
}
declare module 'vis/lib/network/modules/EdgesHandler.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/EdgesHandler'>;
}
declare module 'vis/lib/network/modules/Groups.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/Groups'>;
}
declare module 'vis/lib/network/modules/InteractionHandler.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/InteractionHandler'>;
}
declare module 'vis/lib/network/modules/KamadaKawai.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/KamadaKawai'>;
}
declare module 'vis/lib/network/modules/LayoutEngine.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/LayoutEngine'>;
}
declare module 'vis/lib/network/modules/ManipulationSystem.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/ManipulationSystem'>;
}
declare module 'vis/lib/network/modules/NodesHandler.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/NodesHandler'>;
}
declare module 'vis/lib/network/modules/PhysicsEngine.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/PhysicsEngine'>;
}
declare module 'vis/lib/network/modules/SelectionHandler.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/SelectionHandler'>;
}
declare module 'vis/lib/network/modules/View.js' {
  declare module.exports: $Exports<'vis/lib/network/modules/View'>;
}
declare module 'vis/lib/network/Network.js' {
  declare module.exports: $Exports<'vis/lib/network/Network'>;
}
declare module 'vis/lib/network/NetworkUtil.js' {
  declare module.exports: $Exports<'vis/lib/network/NetworkUtil'>;
}
declare module 'vis/lib/network/options.js' {
  declare module.exports: $Exports<'vis/lib/network/options'>;
}
declare module 'vis/lib/network/shapes.js' {
  declare module.exports: $Exports<'vis/lib/network/shapes'>;
}
declare module 'vis/lib/Queue.js' {
  declare module.exports: $Exports<'vis/lib/Queue'>;
}
declare module 'vis/lib/shared/Activator.js' {
  declare module.exports: $Exports<'vis/lib/shared/Activator'>;
}
declare module 'vis/lib/shared/ColorPicker.js' {
  declare module.exports: $Exports<'vis/lib/shared/ColorPicker'>;
}
declare module 'vis/lib/shared/Configurator.js' {
  declare module.exports: $Exports<'vis/lib/shared/Configurator'>;
}
declare module 'vis/lib/shared/Popup.js' {
  declare module.exports: $Exports<'vis/lib/shared/Popup'>;
}
declare module 'vis/lib/shared/Validator.js' {
  declare module.exports: $Exports<'vis/lib/shared/Validator'>;
}
declare module 'vis/lib/timeline/component/BackgroundGroup.js' {
  declare module.exports: $Exports<'vis/lib/timeline/component/BackgroundGroup'>;
}
declare module 'vis/lib/timeline/component/Component.js' {
  declare module.exports: $Exports<'vis/lib/timeline/component/Component'>;
}
declare module 'vis/lib/timeline/component/CurrentTime.js' {
  declare module.exports: $Exports<'vis/lib/timeline/component/CurrentTime'>;
}
declare module 'vis/lib/timeline/component/CustomTime.js' {
  declare module.exports: $Exports<'vis/lib/timeline/component/CustomTime'>;
}
declare module 'vis/lib/timeline/component/DataAxis.js' {
  declare module.exports: $Exports<'vis/lib/timeline/component/DataAxis'>;
}
declare module 'vis/lib/timeline/component/DataScale.js' {
  declare module.exports: $Exports<'vis/lib/timeline/component/DataScale'>;
}
declare module 'vis/lib/timeline/component/graph2d_types/bar.js' {
  declare module.exports: $Exports<'vis/lib/timeline/component/graph2d_types/bar'>;
}
declare module 'vis/lib/timeline/component/graph2d_types/line.js' {
  declare module.exports: $Exports<'vis/lib/timeline/component/graph2d_types/line'>;
}
declare module 'vis/lib/timeline/component/graph2d_types/points.js' {
  declare module.exports: $Exports<'vis/lib/timeline/component/graph2d_types/points'>;
}
declare module 'vis/lib/timeline/component/GraphGroup.js' {
  declare module.exports: $Exports<'vis/lib/timeline/component/GraphGroup'>;
}
declare module 'vis/lib/timeline/component/Group.js' {
  declare module.exports: $Exports<'vis/lib/timeline/component/Group'>;
}
declare module 'vis/lib/timeline/component/item/BackgroundItem.js' {
  declare module.exports: $Exports<'vis/lib/timeline/component/item/BackgroundItem'>;
}
declare module 'vis/lib/timeline/component/item/BoxItem.js' {
  declare module.exports: $Exports<'vis/lib/timeline/component/item/BoxItem'>;
}
declare module 'vis/lib/timeline/component/item/Item.js' {
  declare module.exports: $Exports<'vis/lib/timeline/component/item/Item'>;
}
declare module 'vis/lib/timeline/component/item/PointItem.js' {
  declare module.exports: $Exports<'vis/lib/timeline/component/item/PointItem'>;
}
declare module 'vis/lib/timeline/component/item/RangeItem.js' {
  declare module.exports: $Exports<'vis/lib/timeline/component/item/RangeItem'>;
}
declare module 'vis/lib/timeline/component/ItemSet.js' {
  declare module.exports: $Exports<'vis/lib/timeline/component/ItemSet'>;
}
declare module 'vis/lib/timeline/component/Legend.js' {
  declare module.exports: $Exports<'vis/lib/timeline/component/Legend'>;
}
declare module 'vis/lib/timeline/component/LineGraph.js' {
  declare module.exports: $Exports<'vis/lib/timeline/component/LineGraph'>;
}
declare module 'vis/lib/timeline/component/TimeAxis.js' {
  declare module.exports: $Exports<'vis/lib/timeline/component/TimeAxis'>;
}
declare module 'vis/lib/timeline/Core.js' {
  declare module.exports: $Exports<'vis/lib/timeline/Core'>;
}
declare module 'vis/lib/timeline/DateUtil.js' {
  declare module.exports: $Exports<'vis/lib/timeline/DateUtil'>;
}
declare module 'vis/lib/timeline/Graph2d.js' {
  declare module.exports: $Exports<'vis/lib/timeline/Graph2d'>;
}
declare module 'vis/lib/timeline/locales.js' {
  declare module.exports: $Exports<'vis/lib/timeline/locales'>;
}
declare module 'vis/lib/timeline/optionsGraph2d.js' {
  declare module.exports: $Exports<'vis/lib/timeline/optionsGraph2d'>;
}
declare module 'vis/lib/timeline/optionsTimeline.js' {
  declare module.exports: $Exports<'vis/lib/timeline/optionsTimeline'>;
}
declare module 'vis/lib/timeline/Range.js' {
  declare module.exports: $Exports<'vis/lib/timeline/Range'>;
}
declare module 'vis/lib/timeline/Stack.js' {
  declare module.exports: $Exports<'vis/lib/timeline/Stack'>;
}
declare module 'vis/lib/timeline/Timeline.js' {
  declare module.exports: $Exports<'vis/lib/timeline/Timeline'>;
}
declare module 'vis/lib/timeline/TimeStep.js' {
  declare module.exports: $Exports<'vis/lib/timeline/TimeStep'>;
}
declare module 'vis/lib/util.js' {
  declare module.exports: $Exports<'vis/lib/util'>;
}
