// flow-typed signature: a099122576a24c7a78325271cdd0048f
// flow-typed version: <<STUB>>/websocket_v^1.0.24/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'websocket'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'websocket' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'websocket/gulpfile' {
  declare module.exports: any;
}

declare module 'websocket/lib/browser' {
  declare module.exports: any;
}

declare module 'websocket/lib/BufferUtil.fallback' {
  declare module.exports: any;
}

declare module 'websocket/lib/BufferUtil' {
  declare module.exports: any;
}

declare module 'websocket/lib/Deprecation' {
  declare module.exports: any;
}

declare module 'websocket/lib/utils' {
  declare module.exports: any;
}

declare module 'websocket/lib/Validation.fallback' {
  declare module.exports: any;
}

declare module 'websocket/lib/Validation' {
  declare module.exports: any;
}

declare module 'websocket/lib/version' {
  declare module.exports: any;
}

declare module 'websocket/lib/W3CWebSocket' {
  declare module.exports: any;
}

declare module 'websocket/lib/websocket' {
  declare module.exports: any;
}

declare module 'websocket/lib/WebSocketClient' {
  declare module.exports: any;
}

declare module 'websocket/lib/WebSocketConnection' {
  declare module.exports: any;
}

declare module 'websocket/lib/WebSocketFrame' {
  declare module.exports: any;
}

declare module 'websocket/lib/WebSocketRequest' {
  declare module.exports: any;
}

declare module 'websocket/lib/WebSocketRouter' {
  declare module.exports: any;
}

declare module 'websocket/lib/WebSocketRouterRequest' {
  declare module.exports: any;
}

declare module 'websocket/lib/WebSocketServer' {
  declare module.exports: any;
}

declare module 'websocket/vendor/FastBufferList' {
  declare module.exports: any;
}

// Filename aliases
declare module 'websocket/gulpfile.js' {
  declare module.exports: $Exports<'websocket/gulpfile'>;
}
declare module 'websocket/index' {
  declare module.exports: $Exports<'websocket'>;
}
declare module 'websocket/index.js' {
  declare module.exports: $Exports<'websocket'>;
}
declare module 'websocket/lib/browser.js' {
  declare module.exports: $Exports<'websocket/lib/browser'>;
}
declare module 'websocket/lib/BufferUtil.fallback.js' {
  declare module.exports: $Exports<'websocket/lib/BufferUtil.fallback'>;
}
declare module 'websocket/lib/BufferUtil.js' {
  declare module.exports: $Exports<'websocket/lib/BufferUtil'>;
}
declare module 'websocket/lib/Deprecation.js' {
  declare module.exports: $Exports<'websocket/lib/Deprecation'>;
}
declare module 'websocket/lib/utils.js' {
  declare module.exports: $Exports<'websocket/lib/utils'>;
}
declare module 'websocket/lib/Validation.fallback.js' {
  declare module.exports: $Exports<'websocket/lib/Validation.fallback'>;
}
declare module 'websocket/lib/Validation.js' {
  declare module.exports: $Exports<'websocket/lib/Validation'>;
}
declare module 'websocket/lib/version.js' {
  declare module.exports: $Exports<'websocket/lib/version'>;
}
declare module 'websocket/lib/W3CWebSocket.js' {
  declare module.exports: $Exports<'websocket/lib/W3CWebSocket'>;
}
declare module 'websocket/lib/websocket.js' {
  declare module.exports: $Exports<'websocket/lib/websocket'>;
}
declare module 'websocket/lib/WebSocketClient.js' {
  declare module.exports: $Exports<'websocket/lib/WebSocketClient'>;
}
declare module 'websocket/lib/WebSocketConnection.js' {
  declare module.exports: $Exports<'websocket/lib/WebSocketConnection'>;
}
declare module 'websocket/lib/WebSocketFrame.js' {
  declare module.exports: $Exports<'websocket/lib/WebSocketFrame'>;
}
declare module 'websocket/lib/WebSocketRequest.js' {
  declare module.exports: $Exports<'websocket/lib/WebSocketRequest'>;
}
declare module 'websocket/lib/WebSocketRouter.js' {
  declare module.exports: $Exports<'websocket/lib/WebSocketRouter'>;
}
declare module 'websocket/lib/WebSocketRouterRequest.js' {
  declare module.exports: $Exports<'websocket/lib/WebSocketRouterRequest'>;
}
declare module 'websocket/lib/WebSocketServer.js' {
  declare module.exports: $Exports<'websocket/lib/WebSocketServer'>;
}
declare module 'websocket/vendor/FastBufferList.js' {
  declare module.exports: $Exports<'websocket/vendor/FastBufferList'>;
}
