// flow-typed signature: efc8a980cb830128a9eaa7f9ee01567b
// flow-typed version: <<STUB>>/ws_v^3.0.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ws'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ws' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ws/lib/BufferUtil' {
  declare module.exports: any;
}

declare module 'ws/lib/Constants' {
  declare module.exports: any;
}

declare module 'ws/lib/ErrorCodes' {
  declare module.exports: any;
}

declare module 'ws/lib/EventTarget' {
  declare module.exports: any;
}

declare module 'ws/lib/Extensions' {
  declare module.exports: any;
}

declare module 'ws/lib/PerMessageDeflate' {
  declare module.exports: any;
}

declare module 'ws/lib/Receiver' {
  declare module.exports: any;
}

declare module 'ws/lib/Sender' {
  declare module.exports: any;
}

declare module 'ws/lib/Validation' {
  declare module.exports: any;
}

declare module 'ws/lib/WebSocket' {
  declare module.exports: any;
}

declare module 'ws/lib/WebSocketServer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ws/index' {
  declare module.exports: $Exports<'ws'>;
}
declare module 'ws/index.js' {
  declare module.exports: $Exports<'ws'>;
}
declare module 'ws/lib/BufferUtil.js' {
  declare module.exports: $Exports<'ws/lib/BufferUtil'>;
}
declare module 'ws/lib/Constants.js' {
  declare module.exports: $Exports<'ws/lib/Constants'>;
}
declare module 'ws/lib/ErrorCodes.js' {
  declare module.exports: $Exports<'ws/lib/ErrorCodes'>;
}
declare module 'ws/lib/EventTarget.js' {
  declare module.exports: $Exports<'ws/lib/EventTarget'>;
}
declare module 'ws/lib/Extensions.js' {
  declare module.exports: $Exports<'ws/lib/Extensions'>;
}
declare module 'ws/lib/PerMessageDeflate.js' {
  declare module.exports: $Exports<'ws/lib/PerMessageDeflate'>;
}
declare module 'ws/lib/Receiver.js' {
  declare module.exports: $Exports<'ws/lib/Receiver'>;
}
declare module 'ws/lib/Sender.js' {
  declare module.exports: $Exports<'ws/lib/Sender'>;
}
declare module 'ws/lib/Validation.js' {
  declare module.exports: $Exports<'ws/lib/Validation'>;
}
declare module 'ws/lib/WebSocket.js' {
  declare module.exports: $Exports<'ws/lib/WebSocket'>;
}
declare module 'ws/lib/WebSocketServer.js' {
  declare module.exports: $Exports<'ws/lib/WebSocketServer'>;
}
