// flow-typed signature: aeca92eaf2f43c625d3be06eb8dc2bc7
// flow-typed version: <<STUB>>/xdg-basedir_v4.0.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xdg-basedir'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'xdg-basedir' {
  declare module.exports: {
    /**
    * Directory for user-specific data files.
    * @example ```js
    * import xdgBasedir = require('xdg-basedir');
    * xdgBasedir.data;
    * //=> '/home/sindresorhus/.local/share'
    * ```
    */
    +data?: string,

    /**
    * Directory for user-specific configuration files.
    * @example ```js
    * import xdgBasedir = require('xdg-basedir');
    * xdgBasedir.config;
    * //=> '/home/sindresorhus/.config'
    * ```
    */
    +config?: string,

    /**
    * Directory for user-specific non-essential data files.
    * @example ```js
    * import xdgBasedir = require('xdg-basedir');
    * xdgBasedir.cache;
    * //=> '/home/sindresorhus/.cache'
    * ```
    */
    +cache?: string,

    /**
    * Directory for user-specific non-essential runtime files and other file objects (such as sockets, named pipes, etc).
    * @example ```js
    * import xdgBasedir = require('xdg-basedir');
    * xdgBasedir.runtime;
    * //=> '/run/user/sindresorhus'
    * ```
    */
    +runtime?: string,

    /**
    * Preference-ordered array of base directories to search for data files in addition to `.data`.
    * @example ```js
    * import xdgBasedir = require('xdg-basedir');
    * xdgBasedir.dataDirs
    * //=> ['/home/sindresorhus/.local/share', '/usr/local/share/', '/usr/share/']
    * ```
    */
    +dataDirs: [string],

    /**
    * Preference-ordered array of base directories to search for configuration files in addition to `.config`.
    * @example ```js
    * import xdgBasedir = require('xdg-basedir');
    * xdgBasedir.configDirs;
    * //=> ['/home/sindresorhus/.config', '/etc/xdg']
    * ```
    */
    +configDirs: [string],
  }
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'xdg-basedir/index' {
  declare module.exports: $Exports<'xdg-basedir'>;
}
declare module 'xdg-basedir/index.js' {
  declare module.exports: $Exports<'xdg-basedir'>;
}
