require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-flipper/react_native_flipper'
source 'https://github.com/CocoaPods/Specs'

platform :ios, '10.0'

# used for automatic bumping
flipperkit_version = '0.93.0'

target 'ReactNativeFlipperExample' do
  config = use_native_modules!
  use_react_native!(
    :path => config["reactNativePath"],
    :hermes_enabled => true
  )

  target 'ReactNativeFlipperExampleTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper' => flipperkit_version, 'Flipper-Folly' => '2.6.7', 'Flipper-RSocket' => '1.4.3', 'Flipper-DoubleConversion' => '3.1.7', 'Flipper-Glog' => '0.3.9', 'Flipper-PeerTalk' => '0.0.4' })
  post_install do |installer|
    flipper_post_install(installer)
    react_native_post_install(installer)

    # based on https://stackoverflow.com/a/37289688/1983583
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
      end
    end
  end
end
