require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
source 'https://github.com/CocoaPods/Specs'

platform :ios, '11.0'

# used for automatic bumping
flipperkit_version = '0.110.0'

target 'ReactNativeFlipperExample' do
  config = use_native_modules!
  use_react_native!(
    :path => config["reactNativePath"],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )

  target 'ReactNativeFlipperExampleTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.

  # Versions are explicitly pinned to be able to forcefully test against the latest versions. 
  # use_flipper!() should work as well and pick the React Native defaults
  use_flipper!({ 'Flipper' => flipperkit_version, 'Flipper-Folly' => '2.6.9', 'Flipper-RSocket' => '1.4.3', 'Flipper-DoubleConversion' => '3.1.7', 'Flipper-Glog' => '0.3.9', 'Flipper-PeerTalk' => '0.0.4' })

  post_install do |installer|
    react_native_post_install(installer)
  end
end
