#!/usr/bin/env bash

SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
NODE_PATH="${SCRIPT_PATH}/node"
SERVER_RESOURCES="$SCRIPT_PATH/../Resources/server"

cd "$SERVER_RESOURCES" || exit 1
echo "Starting flipper-server ..."
"$NODE_PATH" . "$@"
