#!/usr/bin/env bash

set -e

main () {
  local -r THIS_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
  RESOURCES_DIR="$THIS_DIR/../Resources"
  source "$RESOURCES_DIR/setup-env.sh"

  if [ "$CACHE_STATUS" == "none" ]; then
    # we only bring up the terminal when there's no download present
    "/Applications/Utilities/Terminal.app/Contents/MacOS/Terminal" "$RESOURCES_DIR/download-initial.sh"
  else
    # launch the app
    "$RESOURCES_DIR/start.sh" "$@"
  fi
}

main "$@"
