# BUILD FILE SYNTAX: SKYLARK
load("@xplat//configurations/buck/android:fb_android_library.bzl", "fb_android_library")
load("//java/com/facebook/sonar:sonar_defs.bzl", "supported_apps")

fb_android_library(
    name = "sharedpreferences",
    srcs = glob(["*.java"]),
    visibility = ["//java/com/facebook/sonar/..."] + supported_apps,
    deps = [
        "//java/com/facebook/sonar:sonar",
    ],
)
