load("@xplat//configurations/buck/apple:flag_defs.bzl", "get_fbobjc_enable_exception_lang_compiler_flags", "get_fbobjc_xctest_tests_flags", "OBJC_ARC_PREPROCESSOR_FLAGS")
load("@xplat//configurations/buck/apple:fb_apple_library.bzl", "fb_apple_library")

PUBLIC_HEADERS = [
    "SKIOSNetworkAdapter.h",
]

fb_apple_library(
    name = "SKIOSNetworkPlugin",
    srcs = glob([
        "**/*.m",
        "**/*.mm",
    ]),
    headers = glob(
        ["**/*.h"],
        exclude = PUBLIC_HEADERS,
    ),
    exported_headers = PUBLIC_HEADERS,
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
    ],
    lang_compiler_flags = get_fbobjc_enable_exception_lang_compiler_flags(),
    preprocessor_flags = OBJC_ARC_PREPROCESSOR_FLAGS,
    deps = [
        "//Libraries/SonarKit/SonarKitPlugins/OSSPlugins/SonarKitNetworkPlugin:SonarKitNetworkPlugin",
    ],
)
