project 'SampleSwift.xcodeproj'
source 'https://github.com/facebook/Sonar.git'
source 'https://github.com/CocoaPods/Specs'
swift_version = "4.1"

target 'SampleSwift' do
  pod 'SonarKit', :path => '../../SonarKit.podspec'
  pod 'SonarKit/SKIOSNetworkPlugin', :path => '../../SonarKit.podspec'
  pod 'Sonar', :path => '../../Sonar.podspec'
  # Layout and network plugins are not yet supported for swift projects
  #pod 'SonarKit/SonarKitLayoutComponentKitSupport', :path => '../../SonarKit.podspec'

  post_install do |installer|
        installer.pods_project.targets.each do |target|
            if ['YogaKit'].include? target.name
                target.build_configurations.each do |config|
                    config.build_settings['SWIFT_VERSION'] = swift_version
                end
            end
        end
    end

end
