# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SonarKit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  project 'SonarKit.xcodeproj'

  # Pods for SonarKit

    pod 'PeerTalk', :podspec => 'third-party-podspecs/PeerTalk.podspec'
    pod 'RSocket', :podspec => 'third-party-podspecs/RSocket.podspec'
    pod 'DoubleConversion', :podspec => 'third-party-podspecs/DoubleConversion.podspec'
    pod 'glog', :podspec => 'third-party-podspecs/glog.podspec'
    pod 'Folly', :podspec => 'third-party-podspecs/Folly.podspec'
    pod 'Sonar', :podspec => '../xplat/Sonar/Sonar.podspec'
    pod 'CocoaAsyncSocket'
end
