# Uncomment the next line to define a global platform for your project
source 'https://github.com/facebook/flipper.git'
source 'https://github.com/CocoaPods/Specs'
platform :ios, '10.0'
swift_version = "4.1"
target 'FlipperKit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  workspace 'FlipperKit.xcworkspace'
  project 'FlipperKit.xcodeproj'
  pod 'Flipper', :path => '../Flipper.podspec'
  # Pods for SonarKit
  pod 'Flipper-PeerTalk', '~>0.0'
  pod 'DoubleConversion', '~>1.1'
  pod 'glog', '~>0.3'
  pod 'Flipper-Folly', '~>2.2'
  pod 'CocoaAsyncSocket', '~>7.6'
  pod 'SocketRocket', '~> 0.6.0'

end
target 'PortForwardingMacApp' do
  use_frameworks!
  platform :osx, '11'
  workspace 'FlipperKit.xcworkspace'
  project '../PortForwardingMacApp.xcodeproj'
  pod 'Flipper-PeerTalk', '~>0.0'
  pod 'CocoaAsyncSocket', '~>7.6'
end 
