// flow-typed signature: 290caff3b97efa4471b18ff001038a13
// flow-typed version: <<STUB>>/needle_v2.2.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'needle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'needle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'needle/examples/deflated-stream' {
  declare module.exports: any;
}

declare module 'needle/examples/digest-auth' {
  declare module.exports: any;
}

declare module 'needle/examples/download-to-file' {
  declare module.exports: any;
}

declare module 'needle/examples/multipart-stream' {
  declare module.exports: any;
}

declare module 'needle/examples/parsed-stream' {
  declare module.exports: any;
}

declare module 'needle/examples/parsed-stream2' {
  declare module.exports: any;
}

declare module 'needle/examples/stream-events' {
  declare module.exports: any;
}

declare module 'needle/examples/stream-to-file' {
  declare module.exports: any;
}

declare module 'needle/examples/upload-image' {
  declare module.exports: any;
}

declare module 'needle/lib/auth' {
  declare module.exports: any;
}

declare module 'needle/lib/cookies' {
  declare module.exports: any;
}

declare module 'needle/lib/decoder' {
  declare module.exports: any;
}

declare module 'needle/lib/multipart' {
  declare module.exports: any;
}

declare module 'needle/lib/needle' {
  declare module.exports: any;
}

declare module 'needle/lib/parsers' {
  declare module.exports: any;
}

declare module 'needle/lib/querystring' {
  declare module.exports: any;
}

declare module 'needle/test/basic_auth_spec' {
  declare module.exports: any;
}

declare module 'needle/test/compression_spec' {
  declare module.exports: any;
}

declare module 'needle/test/cookies_spec' {
  declare module.exports: any;
}

declare module 'needle/test/decoder_spec' {
  declare module.exports: any;
}

declare module 'needle/test/errors_spec' {
  declare module.exports: any;
}

declare module 'needle/test/headers_spec' {
  declare module.exports: any;
}

declare module 'needle/test/helpers' {
  declare module.exports: any;
}

declare module 'needle/test/long_string_spec' {
  declare module.exports: any;
}

declare module 'needle/test/output_spec' {
  declare module.exports: any;
}

declare module 'needle/test/parsing_spec' {
  declare module.exports: any;
}

declare module 'needle/test/post_data_spec' {
  declare module.exports: any;
}

declare module 'needle/test/proxy_spec' {
  declare module.exports: any;
}

declare module 'needle/test/querystring_spec' {
  declare module.exports: any;
}

declare module 'needle/test/redirect_spec' {
  declare module.exports: any;
}

declare module 'needle/test/redirect_with_timeout' {
  declare module.exports: any;
}

declare module 'needle/test/request_stream_spec' {
  declare module.exports: any;
}

declare module 'needle/test/response_stream_spec' {
  declare module.exports: any;
}

declare module 'needle/test/socket_pool_spec' {
  declare module.exports: any;
}

declare module 'needle/test/url_spec' {
  declare module.exports: any;
}

declare module 'needle/test/utils/formidable' {
  declare module.exports: any;
}

declare module 'needle/test/utils/proxy' {
  declare module.exports: any;
}

declare module 'needle/test/utils/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'needle/examples/deflated-stream.js' {
  declare module.exports: $Exports<'needle/examples/deflated-stream'>;
}
declare module 'needle/examples/digest-auth.js' {
  declare module.exports: $Exports<'needle/examples/digest-auth'>;
}
declare module 'needle/examples/download-to-file.js' {
  declare module.exports: $Exports<'needle/examples/download-to-file'>;
}
declare module 'needle/examples/multipart-stream.js' {
  declare module.exports: $Exports<'needle/examples/multipart-stream'>;
}
declare module 'needle/examples/parsed-stream.js' {
  declare module.exports: $Exports<'needle/examples/parsed-stream'>;
}
declare module 'needle/examples/parsed-stream2.js' {
  declare module.exports: $Exports<'needle/examples/parsed-stream2'>;
}
declare module 'needle/examples/stream-events.js' {
  declare module.exports: $Exports<'needle/examples/stream-events'>;
}
declare module 'needle/examples/stream-to-file.js' {
  declare module.exports: $Exports<'needle/examples/stream-to-file'>;
}
declare module 'needle/examples/upload-image.js' {
  declare module.exports: $Exports<'needle/examples/upload-image'>;
}
declare module 'needle/lib/auth.js' {
  declare module.exports: $Exports<'needle/lib/auth'>;
}
declare module 'needle/lib/cookies.js' {
  declare module.exports: $Exports<'needle/lib/cookies'>;
}
declare module 'needle/lib/decoder.js' {
  declare module.exports: $Exports<'needle/lib/decoder'>;
}
declare module 'needle/lib/multipart.js' {
  declare module.exports: $Exports<'needle/lib/multipart'>;
}
declare module 'needle/lib/needle.js' {
  declare module.exports: $Exports<'needle/lib/needle'>;
}
declare module 'needle/lib/parsers.js' {
  declare module.exports: $Exports<'needle/lib/parsers'>;
}
declare module 'needle/lib/querystring.js' {
  declare module.exports: $Exports<'needle/lib/querystring'>;
}
declare module 'needle/test/basic_auth_spec.js' {
  declare module.exports: $Exports<'needle/test/basic_auth_spec'>;
}
declare module 'needle/test/compression_spec.js' {
  declare module.exports: $Exports<'needle/test/compression_spec'>;
}
declare module 'needle/test/cookies_spec.js' {
  declare module.exports: $Exports<'needle/test/cookies_spec'>;
}
declare module 'needle/test/decoder_spec.js' {
  declare module.exports: $Exports<'needle/test/decoder_spec'>;
}
declare module 'needle/test/errors_spec.js' {
  declare module.exports: $Exports<'needle/test/errors_spec'>;
}
declare module 'needle/test/headers_spec.js' {
  declare module.exports: $Exports<'needle/test/headers_spec'>;
}
declare module 'needle/test/helpers.js' {
  declare module.exports: $Exports<'needle/test/helpers'>;
}
declare module 'needle/test/long_string_spec.js' {
  declare module.exports: $Exports<'needle/test/long_string_spec'>;
}
declare module 'needle/test/output_spec.js' {
  declare module.exports: $Exports<'needle/test/output_spec'>;
}
declare module 'needle/test/parsing_spec.js' {
  declare module.exports: $Exports<'needle/test/parsing_spec'>;
}
declare module 'needle/test/post_data_spec.js' {
  declare module.exports: $Exports<'needle/test/post_data_spec'>;
}
declare module 'needle/test/proxy_spec.js' {
  declare module.exports: $Exports<'needle/test/proxy_spec'>;
}
declare module 'needle/test/querystring_spec.js' {
  declare module.exports: $Exports<'needle/test/querystring_spec'>;
}
declare module 'needle/test/redirect_spec.js' {
  declare module.exports: $Exports<'needle/test/redirect_spec'>;
}
declare module 'needle/test/redirect_with_timeout.js' {
  declare module.exports: $Exports<'needle/test/redirect_with_timeout'>;
}
declare module 'needle/test/request_stream_spec.js' {
  declare module.exports: $Exports<'needle/test/request_stream_spec'>;
}
declare module 'needle/test/response_stream_spec.js' {
  declare module.exports: $Exports<'needle/test/response_stream_spec'>;
}
declare module 'needle/test/socket_pool_spec.js' {
  declare module.exports: $Exports<'needle/test/socket_pool_spec'>;
}
declare module 'needle/test/url_spec.js' {
  declare module.exports: $Exports<'needle/test/url_spec'>;
}
declare module 'needle/test/utils/formidable.js' {
  declare module.exports: $Exports<'needle/test/utils/formidable'>;
}
declare module 'needle/test/utils/proxy.js' {
  declare module.exports: $Exports<'needle/test/utils/proxy'>;
}
declare module 'needle/test/utils/test.js' {
  declare module.exports: $Exports<'needle/test/utils/test'>;
}
