// flow-typed signature: 033193531f49f251b11350a57a58eb12
// flow-typed version: <<STUB>>/react-chartjs-2_vlatest/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-chartjs-2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-chartjs-2' {
  declare module.exports: any;
}
