// flow-typed signature: f8556e312538a69cb4b93dca5618b82a
// flow-typed version: <<STUB>>/react-stepper-horizontal_v1.0.11/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-stepper-horizontal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-stepper-horizontal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-stepper-horizontal/lib' {
  declare module.exports: any;
}

declare module 'react-stepper-horizontal/lib/Step' {
  declare module.exports: any;
}

declare module 'react-stepper-horizontal/lib/Stepper' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-stepper-horizontal/lib/index' {
  declare module.exports: $Exports<'react-stepper-horizontal/lib'>;
}
declare module 'react-stepper-horizontal/lib/index.js' {
  declare module.exports: $Exports<'react-stepper-horizontal/lib'>;
}
declare module 'react-stepper-horizontal/lib/Step.js' {
  declare module.exports: $Exports<'react-stepper-horizontal/lib/Step'>;
}
declare module 'react-stepper-horizontal/lib/Stepper.js' {
  declare module.exports: $Exports<'react-stepper-horizontal/lib/Stepper'>;
}
