// flow-typed signature: 32f203474854b8a1d378914b9461a972
// flow-typed version: <<STUB>>/react-d3-tree_v1.12.0/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-d3-tree'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-d3-tree' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-d3-tree/jest/mocks/cssModule' {
  declare module.exports: any;
}

declare module 'react-d3-tree/jest/mocks/image' {
  declare module.exports: any;
}

declare module 'react-d3-tree/jest/polyfills/raf' {
  declare module.exports: any;
}

declare module 'react-d3-tree/jest/setup' {
  declare module.exports: any;
}

declare module 'react-d3-tree/lib/react-d3-tree.min' {
  declare module.exports: any;
}

declare module 'react-d3-tree/scripts/generateMarkdown' {
  declare module.exports: any;
}

declare module 'react-d3-tree/src/index' {
  declare module.exports: any;
}

declare module 'react-d3-tree/src/Link/index' {
  declare module.exports: any;
}

declare module 'react-d3-tree/src/Link/tests/index.test' {
  declare module.exports: any;
}

declare module 'react-d3-tree/src/Node/ForeignObjectElement' {
  declare module.exports: any;
}

declare module 'react-d3-tree/src/Node/index' {
  declare module.exports: any;
}

declare module 'react-d3-tree/src/Node/SvgTextElement' {
  declare module.exports: any;
}

declare module 'react-d3-tree/src/Node/tests/ForeignObjectElement.test' {
  declare module.exports: any;
}

declare module 'react-d3-tree/src/Node/tests/index.test' {
  declare module.exports: any;
}

declare module 'react-d3-tree/src/Node/tests/SvgTextElement.test' {
  declare module.exports: any;
}

declare module 'react-d3-tree/src/Tree/index' {
  declare module.exports: any;
}

declare module 'react-d3-tree/src/Tree/NodeWrapper' {
  declare module.exports: any;
}

declare module 'react-d3-tree/src/Tree/tests/index.test' {
  declare module.exports: any;
}

declare module 'react-d3-tree/src/Tree/tests/mockData' {
  declare module.exports: any;
}

declare module 'react-d3-tree/src/Tree/tests/NodeWrapper.test' {
  declare module.exports: any;
}

declare module 'react-d3-tree/src/util/index' {
  declare module.exports: any;
}

declare module 'react-d3-tree/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-d3-tree/jest/mocks/cssModule.js' {
  declare module.exports: $Exports<'react-d3-tree/jest/mocks/cssModule'>;
}
declare module 'react-d3-tree/jest/mocks/image.js' {
  declare module.exports: $Exports<'react-d3-tree/jest/mocks/image'>;
}
declare module 'react-d3-tree/jest/polyfills/raf.js' {
  declare module.exports: $Exports<'react-d3-tree/jest/polyfills/raf'>;
}
declare module 'react-d3-tree/jest/setup.js' {
  declare module.exports: $Exports<'react-d3-tree/jest/setup'>;
}
declare module 'react-d3-tree/lib/react-d3-tree.min.js' {
  declare module.exports: $Exports<'react-d3-tree/lib/react-d3-tree.min'>;
}
declare module 'react-d3-tree/scripts/generateMarkdown.js' {
  declare module.exports: $Exports<'react-d3-tree/scripts/generateMarkdown'>;
}
declare module 'react-d3-tree/src/index.js' {
  declare module.exports: $Exports<'react-d3-tree/src/index'>;
}
declare module 'react-d3-tree/src/Link/index.js' {
  declare module.exports: $Exports<'react-d3-tree/src/Link/index'>;
}
declare module 'react-d3-tree/src/Link/tests/index.test.js' {
  declare module.exports: $Exports<'react-d3-tree/src/Link/tests/index.test'>;
}
declare module 'react-d3-tree/src/Node/ForeignObjectElement.js' {
  declare module.exports: $Exports<'react-d3-tree/src/Node/ForeignObjectElement'>;
}
declare module 'react-d3-tree/src/Node/index.js' {
  declare module.exports: $Exports<'react-d3-tree/src/Node/index'>;
}
declare module 'react-d3-tree/src/Node/SvgTextElement.js' {
  declare module.exports: $Exports<'react-d3-tree/src/Node/SvgTextElement'>;
}
declare module 'react-d3-tree/src/Node/tests/ForeignObjectElement.test.js' {
  declare module.exports: $Exports<'react-d3-tree/src/Node/tests/ForeignObjectElement.test'>;
}
declare module 'react-d3-tree/src/Node/tests/index.test.js' {
  declare module.exports: $Exports<'react-d3-tree/src/Node/tests/index.test'>;
}
declare module 'react-d3-tree/src/Node/tests/SvgTextElement.test.js' {
  declare module.exports: $Exports<'react-d3-tree/src/Node/tests/SvgTextElement.test'>;
}
declare module 'react-d3-tree/src/Tree/index.js' {
  declare module.exports: $Exports<'react-d3-tree/src/Tree/index'>;
}
declare module 'react-d3-tree/src/Tree/NodeWrapper.js' {
  declare module.exports: $Exports<'react-d3-tree/src/Tree/NodeWrapper'>;
}
declare module 'react-d3-tree/src/Tree/tests/index.test.js' {
  declare module.exports: $Exports<'react-d3-tree/src/Tree/tests/index.test'>;
}
declare module 'react-d3-tree/src/Tree/tests/mockData.js' {
  declare module.exports: $Exports<'react-d3-tree/src/Tree/tests/mockData'>;
}
declare module 'react-d3-tree/src/Tree/tests/NodeWrapper.test.js' {
  declare module.exports: $Exports<'react-d3-tree/src/Tree/tests/NodeWrapper.test'>;
}
declare module 'react-d3-tree/src/util/index.js' {
  declare module.exports: $Exports<'react-d3-tree/src/util/index'>;
}
declare module 'react-d3-tree/webpack.config.js' {
  declare module.exports: $Exports<'react-d3-tree/webpack.config'>;
}
