// flow-typed signature: 21bf70a7f73a77579f4cc048adda0919
// flow-typed version: <<STUB>>/sql-formatter_v2.3.3/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sql-formatter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sql-formatter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sql-formatter/dist/sql-formatter' {
  declare module.exports: any;
}

declare module 'sql-formatter/dist/sql-formatter.min' {
  declare module.exports: any;
}

declare module 'sql-formatter/lib/core/Formatter' {
  declare module.exports: any;
}

declare module 'sql-formatter/lib/core/Indentation' {
  declare module.exports: any;
}

declare module 'sql-formatter/lib/core/InlineBlock' {
  declare module.exports: any;
}

declare module 'sql-formatter/lib/core/Params' {
  declare module.exports: any;
}

declare module 'sql-formatter/lib/core/Tokenizer' {
  declare module.exports: any;
}

declare module 'sql-formatter/lib/core/tokenTypes' {
  declare module.exports: any;
}

declare module 'sql-formatter/lib/languages/Db2Formatter' {
  declare module.exports: any;
}

declare module 'sql-formatter/lib/languages/N1qlFormatter' {
  declare module.exports: any;
}

declare module 'sql-formatter/lib/languages/PlSqlFormatter' {
  declare module.exports: any;
}

declare module 'sql-formatter/lib/languages/StandardSqlFormatter' {
  declare module.exports: any;
}

declare module 'sql-formatter/lib/sqlFormatter' {
  declare module.exports: any;
}

declare module 'sql-formatter/src/core/Formatter' {
  declare module.exports: any;
}

declare module 'sql-formatter/src/core/Indentation' {
  declare module.exports: any;
}

declare module 'sql-formatter/src/core/InlineBlock' {
  declare module.exports: any;
}

declare module 'sql-formatter/src/core/Params' {
  declare module.exports: any;
}

declare module 'sql-formatter/src/core/Tokenizer' {
  declare module.exports: any;
}

declare module 'sql-formatter/src/core/tokenTypes' {
  declare module.exports: any;
}

declare module 'sql-formatter/src/languages/Db2Formatter' {
  declare module.exports: any;
}

declare module 'sql-formatter/src/languages/N1qlFormatter' {
  declare module.exports: any;
}

declare module 'sql-formatter/src/languages/PlSqlFormatter' {
  declare module.exports: any;
}

declare module 'sql-formatter/src/languages/StandardSqlFormatter' {
  declare module.exports: any;
}

declare module 'sql-formatter/src/sqlFormatter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sql-formatter/dist/sql-formatter.js' {
  declare module.exports: $Exports<'sql-formatter/dist/sql-formatter'>;
}
declare module 'sql-formatter/dist/sql-formatter.min.js' {
  declare module.exports: $Exports<'sql-formatter/dist/sql-formatter.min'>;
}
declare module 'sql-formatter/lib/core/Formatter.js' {
  declare module.exports: $Exports<'sql-formatter/lib/core/Formatter'>;
}
declare module 'sql-formatter/lib/core/Indentation.js' {
  declare module.exports: $Exports<'sql-formatter/lib/core/Indentation'>;
}
declare module 'sql-formatter/lib/core/InlineBlock.js' {
  declare module.exports: $Exports<'sql-formatter/lib/core/InlineBlock'>;
}
declare module 'sql-formatter/lib/core/Params.js' {
  declare module.exports: $Exports<'sql-formatter/lib/core/Params'>;
}
declare module 'sql-formatter/lib/core/Tokenizer.js' {
  declare module.exports: $Exports<'sql-formatter/lib/core/Tokenizer'>;
}
declare module 'sql-formatter/lib/core/tokenTypes.js' {
  declare module.exports: $Exports<'sql-formatter/lib/core/tokenTypes'>;
}
declare module 'sql-formatter/lib/languages/Db2Formatter.js' {
  declare module.exports: $Exports<'sql-formatter/lib/languages/Db2Formatter'>;
}
declare module 'sql-formatter/lib/languages/N1qlFormatter.js' {
  declare module.exports: $Exports<'sql-formatter/lib/languages/N1qlFormatter'>;
}
declare module 'sql-formatter/lib/languages/PlSqlFormatter.js' {
  declare module.exports: $Exports<'sql-formatter/lib/languages/PlSqlFormatter'>;
}
declare module 'sql-formatter/lib/languages/StandardSqlFormatter.js' {
  declare module.exports: $Exports<'sql-formatter/lib/languages/StandardSqlFormatter'>;
}
declare module 'sql-formatter/lib/sqlFormatter.js' {
  declare module.exports: $Exports<'sql-formatter/lib/sqlFormatter'>;
}
declare module 'sql-formatter/src/core/Formatter.js' {
  declare module.exports: $Exports<'sql-formatter/src/core/Formatter'>;
}
declare module 'sql-formatter/src/core/Indentation.js' {
  declare module.exports: $Exports<'sql-formatter/src/core/Indentation'>;
}
declare module 'sql-formatter/src/core/InlineBlock.js' {
  declare module.exports: $Exports<'sql-formatter/src/core/InlineBlock'>;
}
declare module 'sql-formatter/src/core/Params.js' {
  declare module.exports: $Exports<'sql-formatter/src/core/Params'>;
}
declare module 'sql-formatter/src/core/Tokenizer.js' {
  declare module.exports: $Exports<'sql-formatter/src/core/Tokenizer'>;
}
declare module 'sql-formatter/src/core/tokenTypes.js' {
  declare module.exports: $Exports<'sql-formatter/src/core/tokenTypes'>;
}
declare module 'sql-formatter/src/languages/Db2Formatter.js' {
  declare module.exports: $Exports<'sql-formatter/src/languages/Db2Formatter'>;
}
declare module 'sql-formatter/src/languages/N1qlFormatter.js' {
  declare module.exports: $Exports<'sql-formatter/src/languages/N1qlFormatter'>;
}
declare module 'sql-formatter/src/languages/PlSqlFormatter.js' {
  declare module.exports: $Exports<'sql-formatter/src/languages/PlSqlFormatter'>;
}
declare module 'sql-formatter/src/languages/StandardSqlFormatter.js' {
  declare module.exports: $Exports<'sql-formatter/src/languages/StandardSqlFormatter'>;
}
declare module 'sql-formatter/src/sqlFormatter.js' {
  declare module.exports: $Exports<'sql-formatter/src/sqlFormatter'>;
}
