name:                bump
version:             0.2.7

dependencies:
  - base >= 4.7 && < 5
  - turtle
  - system-filepath
  - foldl
  - text

executables:
  bump:
    source-dirs:      .
    main:             bump.hs
    ghc-options:      -optl-static -optl-pthread -fPIC
