load("@xplat//configurations/buck/apple:flag_defs.bzl", "get_fbobjc_enable_exception_lang_compiler_flags", "OBJC_ARC_PREPROCESSOR_FLAGS")
load("@xplat//configurations/buck/apple:fb_apple_library.bzl", "fb_apple_library")

CK_SUPPORT_HEADERS = [
    "SonarKitLayoutComponentKitSupport.h",
    "SKComponentLayoutWrapper.h",
]

fb_apple_library(
    name = "SonarKitLayoutComponentKitSupport",
    srcs = glob([
        "**/*.m",
        "**/*.mm",
    ]),
    headers = glob(
        ["**/*.h"],
        exclude = CK_SUPPORT_HEADERS,
    ),
    exported_headers = CK_SUPPORT_HEADERS,
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
    ],
    lang_compiler_flags = get_fbobjc_enable_exception_lang_compiler_flags(),
    preprocessor_flags = OBJC_ARC_PREPROCESSOR_FLAGS,
    deps = [
        "//Libraries/SonarKit:SonarKit",
        "//Libraries/SonarKit/SonarKitPlugins/OSSPlugins/SonarKitLayoutPlugin:SonarKitLayoutPlugin",
        "//VendorLib/ComponentKit:ComponentKit",
    ],
)
