# BUILD FILE SYNTAX: SKYLARK
load("@xplat//configurations/buck/android:fb_android_library.bzl", "fb_android_library")
load("//java/com/facebook/sonar:sonar_defs.bzl", "supported_apps")

fb_android_library(
    name = "console",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//java/com/facebook/sonar/plugins/oss/console/iface:iface",
    ],
    tests = ["//javatests/com/facebook/sonar/plugins/oss/console:console"],
    visibility = ["//java/com/facebook/sonar/..."] + supported_apps,
    deps = [
        "//java/com/facebook/sonar:sonar",
        "//java/com/facebook/sonar/plugins/oss/console/iface:iface",
        "//third-party/java/rhino:rhino",
    ],
)
