name: Docs
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install and Build
        run: |
          yarn
          yarn  build
        working-directory: website/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: website/build
          clean: true
          clean-exclude: |
            .circleci
          commit-message: "[ci skip] Deploying documentation update"
