name: js-flipper
# This action runs on 'git push' and PRs
on: [push, pull_request]

jobs:
  test-js-flipper:
    defaults:
      run:
        working-directory: js/js-flipper
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.3
    - uses: actions/setup-node@v3.6.0
      with:
        node-version: '18.x'
    - name: yarn install (with retry)
      uses: nick-fields/retry@v2.8.3
      with:
        command: cd js/js-flipper && yarn
        timeout_minutes: 30
        max_attempts: 3
    - name: lint
      run: yarn lint
    - name: test
      run: yarn test --coverage

  build-react-example:
    defaults:
      run:
        working-directory: js/react-flipper-example
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.3
    - uses: actions/setup-node@v3.6.0
      with:
        node-version: '18.x'
    - name: js-flipper - yarn install (with retry)
      uses: nick-fields/retry@v2.8.3
      with:
        command: cd js/js-flipper && yarn
        timeout_minutes: 30
        max_attempts: 3
    - name: js-flipper build
      run: yarn build
      working-directory: js/js-flipper
    - name: yarn install (with retry)
      uses: nick-fields/retry@v2.8.3
      with:
        command: cd js/react-flipper-example && yarn
        timeout_minutes: 30
        max_attempts: 3
    - name: link local js-flipper
      run: yarn relative-deps
    - name: build
      run: yarn build
