name: Doctor Node CI

on: [push, pull_request]

jobs:
  build:

    runs-on: 'ubuntu-latest'

    env:
      doctor-directory: ./desktop/doctor

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    - name: install
      working-directory: ${{env.doctor-directory}}
      run: yarn
    - name: run
      working-directory: ${{env.doctor-directory}}
      run: yarn run run
