#!/bin/bash
# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

env TS_NODE_TRANSPILE_ONLY=true node --require ts-node/register "$@"
